### ISSUE TITLE
VZE: Matrix of PII fields (public vs standard extract)

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#104]
Currently the database has PII stored. It takes 1 API key leaking to expose all data. This raises some security issues:

• What sensitive fields need to be displayed in VZE?
• Should we limit access with a VPN on Hasura? could use existing VPN with list/range of IP address.

Questions for VZ team:
- if someone requested a CR3, what (if anything) would be redacted?
- what PII do you need to track over time?
- See also ScrAPD for publicly released last names, gender, ethnicity, etc

**Comment by mateoclarke** [comment]
- [ ] give a list of PII and share with Joel/Lewis and recommend which fields we think they should retain (@johnclary you to put this together? I can take a first pass if you want)
- We should flag PII fields in VZD #154 
- [ ] Lewis to ask APD if/how they release CR3s
- Zipcode is important to keep
- We don't need the DL #

**Comment by johnclary** [comment]
@mateoclarke i took a first pass: https://docs.google.com/spreadsheets/d/1gLKKDOGYde2WzlFTcCSHrQcYuLwdAvTCk8tQ6LjjdOY/edit#gid=0

**Comment by johnclary** [comment]
also want to stress that, even with the fields listed on the matrix as "ok to retain", we should not retain that info unless it's actually needed by staff

**Comment by amenity** [comment]
@mateoclarke made an issue for next steps - #166.
