### ISSUE TITLE
VZD: Add Lookup tables to Postgres

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#109]
Theres a bunch of them that end in `_LKP` and we'll need a bunch of them. Ex: Car make/models, injury severity codes, weather conditions, etc

https://drive.google.com/file/d/1pMvWsBGpcveLDNQ8WVwqmT-0oxkyTeGl/view

**Comment by sergiogcx** [comment]
All the lookup tables have been added, we now have a total of 99 tables (no worries, not all are being tracked by hasura).

If you need a full list, go to our database endpoint:
https://vzd.austintexas.io/console/data/schema/public

**Comment by sergiogcx** [comment]
The tables are up and running if you want to give them a try, to use just make sure you track them.

**Comment by mateoclarke** [comment]
works great, closing this out...
