### ISSUE TITLE
Knack: Turn DB entity relationship diagram into Knack Tables

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#14]
- map out connections
- list out attributes and data types for all tables

https://drive.google.com/file/d/1oFzvdmVGYivzLN8_q1oSJ0f6K

![Screen Shot 2019-05-14 at 6 36 02 PM](https://user-images.githubusercontent.com/5697474/57738935-29717d00-7677-11e9-959c-b29c5790a816.png)
pEGrPx5/view

**Comment by johnclary** [comment]
In progress. Knack app is here:
https://builder.knack.com/atd/vision-zero

**Comment by mateoclarke** [comment]
@johnclary just needs to clean up the fields we don't want based on fieldmap excel doc from JM

**Comment by mateoclarke** [comment]
https://drive.google.com/file/d/1pMvWsBGpcveLDNQ8WVwqmT-0oxkyTeGl/view?usp=sharing

**Comment by sergiogcx** [comment]
We can look at this tomorrow at the architecture meeting. The data is mapped ready to be inserted and the tables are ready for knack.
