### ISSUE TITLE
VZD: Add "Confirmed" Crash Address Columns

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-vz-data#146]
There are multiple address columns in the `crash` table. As we've done with lat/lon, we need to add a series of `_confirmed` columns for the address attributes.

**Comment by sergiogcx** [comment]
@johnclary I noticed there are a series of colums including block number, street prefix, name, suffix, etc., the same happens for the secondary address.

Would it be best to have it as two columns with all those values concatenated?

**Comment by sergiogcx** [comment]
After speaking with John, it was determined to implement two columns:

`address_confirmed_primary` and `address_confirmed_secondary`

- [ ] The database should be able to concatenate automatically
- [ ] The database should also allow a manual override.

**Comment by mateoclarke** [comment]
Proposing that we just use these 4 columns in the concatenation:

```
    rpt_street_pfx
    rpt_block_num
    rpt_street_name
    rpt_street_sfx
```

**Comment by sergiogcx** [comment]
The update/insert trigger for crashes now includes the logic to allow for manual updates or automatic updates if no confirmed data is present:

![Screen Shot 2019-09-06 at 2.23.10 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/c2df7813-90b2-493e-b4c5-7ef467261ba7)

![Screen Shot 2019-09-06 at 2.23.41 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/f2cb4816-18a3-404e-879d-790c90138493)

**Comment by sergiogcx** [comment]
All crash records have been updated, the trigger was temporarily disabled, and re-enabled accordingly to avoid a trigger-blitz.

**Comment by sergiogcx** [comment]
It is worth mentioning that after any insertion or update, the address will be automatically updated if no manual data is already present or defined in the insertion query.

**Comment by sergiogcx** [comment]
Closing, the trigger has been tested and works.
