### ISSUE TITLE
VZD: Additional "crash cost" field on Crash Table

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#148]
At least one or more additional field per crash which quantifies the value of life lost, property damage, etc.

We might need to circle back with Lewis to get an appropriate label for this attribute.
`crash_cost` or `damage_value` are some ideas I'm thinking of recalling our convo.

There was also a discussion about how we might automate this calculation using the number of serious injuries and deaths. Wondering if those cost values might change over time. I would guess so.

**Comment by mateoclarke** [comment]
From [SR 3 Question doc](https://docs.google.com/document/d/1mtZoyj0zuTRbgNHiKNJXJK1_Pr5YnOvvLqut1azzcjM/edit#):

>
- there should be two separate columns/fields: 
  - one column for “Estimated Comprehensive Cost by Crash Severity” - maybe labeled “Est_Comp_Cost” -- this can be auto updated based on a formula tied to injury severity field.  
  - One column for years of life lost as laid out below
- They should auto populate based on the following:
  - Est Comp Cost: We are working on what values we will use through the UT research project, but if you want to plug in values for now, you could use [this link](https://www.nsc.org/Portals/0/Documents/NSCDocuments_Corporate/estimating-costs.pdf) to look at “Average Comprehensive Cost…” in the right side table on page one. So it would need to determine what is the severity of each injured person in the crash, and then multiply that by the dollar value in that table. (It may take assigning a number proxy to the person file by injury severity then you could multiply that by the value?)
  - Years of life lost: (75 - age of person killed) 
    - The Person File has a field “Prsn_Age” that can be used.
- Dashboard could have a summary of both values for prior full years, and year-to-date
  - Est Comp Cost = ∑(all values calculated)
  - Years of Life Lost (“YOLL”?) = ∑(75 - age of person killed) for all fatalities.
- Note that both of the above are tied to the injury severity of people, not crashes.

It sounds like we might also need a new lookup table to store input values for the total cost calculation. The link they referenced is from 2015 and it sounds like newer values are being developed with UT right now:
https://www.nsc.org/Portals/0/Documents/NSCDocuments_Corporate/estimating-costs.pdf

**Comment by sergiogcx** [comment]
To begin with, I've implemented two lookup tables:

`atd_txdot__est_comp_cost`

```
est_comp_cost_id,est_comp_cost_desc,est_comp_cost_amount
0,None,0
1,Death,10082000
2,Disabling,1103000
3,Evident,304000
4,Possible injury,141000
5,No injury observed,46600
```

And `atd_txdot__est_econ_cost`

```
est_econ_cost_id,est_econ_cost_desc,est_econ_cost_amount
0,None,0
1,Death (K),1542000
2,Disabling (A),90000
3,Evident (B),26000
4,Possible ( C),21400
5,No injury observed (O),11400
6,Property damage only (cost per vehicle),4200
```

**Comment by sergiogcx** [comment]
So this is now being addressed by a few new lines in the trigger, both comprehensive cost and economic costs are calculated by this trigger automatically after a crash is created or updated.

The numbers were tested using Excel with a sample row:
![Screen Shot 2019-09-24 at 10.19.34 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/39f91cd2-5f3a-457e-a2d0-c539612b6b8e)

Notice both the Trigger-calculated values are the same as the totals directly above them.

**Comment by sergiogcx** [comment]
Now part of production, closing.
