### ISSUE TITLE
VZD: [Question] How many records changed in the dataset if you pull the data again?

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#150]
We can compare records in our two extracts and figure out a way to keep track of this once we unpause the automated extract.

**Comment by sergiogcx** [comment]
@mateoclarke meaning we would pull the entire dataset? (from five years ago)

**Comment by mateoclarke** [comment]
@sergiogcx No sorry, I thought you just requested an extract yesterday that covered July to now. Just changes in records in that time would start to give us more of an idea what to expect.

**Comment by sergiogcx** [comment]
There were 2400 records pulled in, out of which 650 already existed. A few dozen had important changes, some records were missing given the dates, meaning they should have been part of the large initial pull given the dates, but they were not meaning they were not available in CRIS at the time we made the request.

**Comment by sergiogcx** [comment]
Closing this issue, it seems clear that we will need to query a few months back at a time (if not from the beginning of the year) every time we run the ETL process.

No big deal, as long as we allow 2 hours for the database to recover IOPS, we should be able to UPSERT records to postgres methodically as described in related issue: #137

Closing

**Comment by mateoclarke** [comment]
👍 ⚡️

**Comment by amenity** [comment]
@sergiogcx @mateoclarke @johnclary - let's discuss in person what the implications are for our QA process.
