### ISSUE TITLE
VZD/E: Update format for address column on Crash Index page

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#151]
Address Fields: We need Block # + Street Name +Street Suffix near Secondary Street (if it exists)

ex: `8700 Cameron Rd near Cross Point` or just `8700 Cameron Rd` when no secondary street exists.

Currently we display when there are null values so we should hide these in our logic.

- [x] standardize naming in VZD, and a new column `crash_location_name`
- [x] implement triggers to update this new column when primary or secondary columns change
- [x] update the Crash tables in VZE to use new column instead of primary/secondary address columns

_in the future, the associated Location name from the Location table would preempt this and we could drop this column and its triggers_

**Comment by sergiogcx** [comment]
The addresses have been switched to use the confirmed primary and secondary:
https://github.com/cityofaustin/atd-vz-data/pull/186

**Comment by sergiogcx** [comment]
Merged to master, closing.
