### ISSUE TITLE
VZE: Add new columns to Crash Index table.

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#152]
1. Add a column that is a concatenation of the different units
   - this would probably be a comma-separated list of all the related units. One complication is the description you get for motor vehicles vs ped/cyclist. We might need some if/else logic to have the most descriptive information if necessary. 
     - ex: `atd_txdot_units.body_style.veh_body_styl_desc` returns values like "PICKUP" and "PASSENGER CAR, 4-DOOR"
     - `atd_txdot_units.unit_description.veh_unit_desc_desc` returns values like "MOTOR VEHICLE", "PEDESTRIAN", and "PEDALCYCLIST"
   - John suggests: (how about icons for each type?)
2. crash type (aka Manner of Collision) column `fhe_collsn_id`
    - requires new lookup id table tracking to FHE_COLLSN_ID and new relationship connection.

**Comment by mateoclarke** [comment]
- [ ] alpha sort concatenated vehicle body style descriptions

**Comment by sergiogcx** [comment]
I've got it, very tricky but now part of the abstract library:

![Screen_Shot_2019-09-19_at_3_55_10_PM.jpg](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/266019aa-9751-4e1c-b9e3-762c5c9999c0)

**Comment by sergiogcx** [comment]
PR:
https://github.com/cityofaustin/atd-vz-data/pull/188

**Comment by sergiogcx** [comment]
Merged to master, closing.
