### ISSUE TITLE
VZD: update Hasura role permissions for columns that are contain PII

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#154]
There was a discussion about adding `_pii` to the end of all column headers that have PII. But this might break a bunch of queries so the devs has some hesitancy to do this. Maybe starting with a list for documentation and adding db metadata as a first step and we'll see if that is sufficient to update the roles in Hasura.

**Comment by johnclary** [comment]
No longer needed because we're not keeping PII in VZD. Closing.

**Comment by mateoclarke** [comment]
we're going to drop PII fields so no need for this task
