### ISSUE TITLE
VZD: Update Hasura roles for access

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#155]
Hasura Roles for access requirements:

As an IT supervisor, I want to:

Grant a user Admin permissions
Revoke a user's Admin permissions
Create an account
Edit an account's roles
Deactivate an account
Edit all VZE fields
View all VZE pages
Ensure that COA employees lose access to VZE when they no longer work for the City of Austin
As an admin user, I want to be able to do the following:

Create an account
Edit an account's roles
Deactivate an account
Edit all VZE fields
View all VZE pages
As a user with edit access, I want to be able to do the following:

Edit all VZE fields
View all VZE pages
As a user with read-only access, I want to be able to do the following:

View Dashboard page
View Crashes page
View crash details pages
View locations page
View locations details pages

Old Requirements below
___

Related to #154 

In Sprint Review #3 we defined 3 types of users:

1. External to ATD (contractors, temp interns, research partners)
2. Internal ATD Staff
3. VZ program stakeholders.

We need to further define the difference in terms of access for groups 1 & 2.

**Comment by JaceDeloney** [comment]
I'm not sure that this issue is still needed. I have added requirements for Account Management to the VZE | Account Management epic #606
