### ISSUE TITLE
VZE: Location layer creation tasks from sprint review #3

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#157]
Layer creation

- possibly create a hotspot map of high injuries and fatalities from most recent five years
- in combination with high-injury network
- [ ] get criteria from engineering
- create a base polygon layer
- ideally get 500 locations QA'd
- [ ] vz team to let us know priority
- [x] get @frankhereford  what he needs

**Comment by mateoclarke** [comment]
@johnclary, I took this pretty verbatim from your notes. Could you clarify what needs to be actionable here, for who, and how it dovetails with existing open issues around Locations layer?

**Comment by johnclary** [comment]
We agreed w/ VZ team that this is a large undertaking and that we require some prioritization method to begin this work (such as creating a heatmap of priority areas based on crash density), as well as engineer input to establish some kind of baseline methodology for identifying an intersection’s geometry—specifically, a radius from the intersection point, based on road class. 
We need the VZ team to (1) work with engineering to determine the baseline specification for determining the intersection’s area, and (2) prioritize this task against Frank’s geocoding task.

**Comment by JaceDeloney** [comment]
This is an outdated issue. Closing
