### ISSUE TITLE
VZD: Define attributes of Locations

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#158]
Location records represent a discrete geographic area which serves as a unit of analysis for prioritizing and addressing safety issues. We need clarification on what attributes of the location need to be tracked.

The VZ team mentioned:
- lane configuration/traffic pattern
- ped infrastructure: sidewalks, cross walks, etc
- signaling: pedestrian signals (walk/don't walk, countown timers), lead time, protected left turn, bike signals, audible push buttons, etc.
- traffic studies/volume counts
- tracking of interventions/modifications (e.g., installation of countdown timers)

We need the Vision Zero to provide an initial list of attributes and we will map them to current/planned data sources.

**Comment by mateoclarke** [comment]
@johnclary This is another one from your notes that seems like something need to happen but I'm unsure who or how.

**Comment by johnclary** [comment]
@mateoclarke updated the description. We need input from Lewis and team.

**Comment by mateoclarke** [comment]
- [ ] Turn Location attributes data types wishlist into spreadsheet of status of data source and level of effort to incorporate

Using this list as a starting point:
https://docs.google.com/document/d/1mtZoyj0zuTRbgNHiKNJXJK1_Pr5YnOvvLqut1azzcjM/edit#heading=h.57og2re8dos6

**Comment by johnclary** [comment]
Not mvp. Backlogging.

**Comment by JaceDeloney** [comment]
Moved this to needs scoping. We will work with VZ team to identify these attributes and then plan accordingly.
