### ISSUE TITLE
VZE: Modify CSV export to include more than what is displayed in view

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-vz-data#161]
Need more feedback from the Vision Zero Team on use cases of exporting CSVs. Moved from #144 to close that out.

Need to think about whether it makes sense to preserve existing function (export only rows and columns displayed and select # of records by setting "Rows per page") or to extend functionality to allow choosing columns and number of records before export.

**Comment by mateoclarke** [comment]
From the [SR 3 Questions doc](https://docs.google.com/document/d/1mtZoyj0zuTRbgNHiKNJXJK1_Pr5YnOvvLqut1azzcjM/edit#):

>
- LL: to use within BI tool to perform a variety of analysis
  - Columns for the types of analysis I could see:  the standard details (date/time/case ID/street info/conditions/contributing factors/crash location details/etc.) AND most frequent collision types (collsn_desc), most frequent zip codes based on home address of drivers at fault (unit 1 drivers) (ownr_zip), race/ethnicity breakdown of at fault drivers/injured persons (prsn_ethnicity_ID), average posted speed of severe crashes (crash_speed_limit), breakdown of top contributing factors (all “contrib_factr_#), breakdown of mode (veh_unit_desc_desc), breakdown of age of vehicle involved in crashes (veh_mod_year), split of city vs. state road (hwy_sys)
  - I’d expect five years of data to be the maximum we’d ever use.
- Daniel should probably weigh in as he has frequent data requests 
  - Comparing before and after for 2016 bond projects - need five years before 
  - Comparing before and after for red light cameras - dating back to 2010
  - DY: the bullets look good

**Comment by mddilley** [comment]
Feedback from LL (10/6/19):
>Following up on what I see when trying to use the export function in the Vision Zero Editor.  It’d be best if search results could be exported as .xls or .csv format, and any records exported could have all available fields not just the visible fields in the editor interface. I use Firefox mostly, but tried it in Chrome and basically the same thing happened. Let me know if I should be doing something different on my end.
>
>This is the prompt I see when I try to download a search result:
>
>![image002](https://user-images.githubusercontent.com/37249039/66323877-1a22f280-e8ea-11e9-82a8-84297bdea4f2.jpg)
>
>When I attempt to open the file with Excel it says file format and extension doesn’t match, but I accept anyhow and this happens:
>
>![image006](https://user-images.githubusercontent.com/37249039/66323889-1f803d00-e8ea-11e9-8686-e7b0a344d1f1.jpg)

**Comment by amenity** [comment]
Temporary workaround: Have Lewis specify extension before opening.

**Comment by amenity** [comment]
@sergiogcx - can you confirm that the workaround works :), please?
