### ISSUE TITLE
VZD: Talk to Technical Folks at TxDOT About CRIS Data Needs

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-vz-data#164]
It'd be really nice to talk to the technical folks who manage the CRIS database. Two points of discussion:

1. Can we get API access to the CRIS DB (without spoofing their Angular app), or at least an FTP record dump?
2. Would they consider adding a `created_date` date field so that we easily fetch records we don't have. This may not be necessary if we can solve #1.

**Comment by johnclary** [comment]
Added this to the [VZ team todos](https://docs.google.com/document/d/1mtZoyj0zuTRbgNHiKNJXJK1_Pr5YnOvvLqut1azzcjM/edit).

**Comment by sergiogcx** [comment]
It sounds like we are going to re-convene next week, during the conversation Larbi mentioned that they can set up something like they provide to ATD via SFTP, or a custom setup.

**Comment by johnclary** [comment]
@mateoclarke to check-in with Auzzie about this.

The latest:
>Hi Larbi –
>
> Thanks for the call today.  I’m tied up for the afternoon but wanted to make sure I captured what you said correctly and passed it along to the team.
>
> You stated that you all would provide a daily file capturing all crashes in the City of Austin geographic boundaries, all jurisdictions and all fields would be included, and would send these daily updates by FTP to the same location where the APD file is sent.  And we would have to coordinate with Auzzie at APD to gain access to the file.  Is all that right?

**Comment by mateoclarke** [comment]
@johnclary Auzzie says its the City's FTP site, not specific to AUSPS. She's worried about the configuration and doesn't want TxDOT to put the extract in the same folder. She's proposing we set up a time to talk to Larbi. I'm going to cc her into the email exchange and hopefully get a time scheduled.

**Comment by mateoclarke** [comment]
Notes from this meeting sent via email. New issues created from it to be created.
