### ISSUE TITLE
VZD: Drop PII field in Postgres databases

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#166]
Continuing from #104

**Comment by mateoclarke** [comment]
In discussions post-SR#3 we learned that APD only redacts primary person residence address and maybe DOB when there is a PIR for CR3 records.

We have a matrix of which columns we recommend retaining/dropping from our VZD database. Next step is to confirm with LL:
https://docs.google.com/spreadsheets/d/1gLKKDOGYde2WzlFTcCSHrQcYuLwdAvTCk8tQ6LjjdOY/edit#gid=0

**Comment by mateoclarke** [comment]
After emails and discussions in Sprint Review #5 we've decided to go ahead and drop the PII columns from VZD. 

Let's make sure do this for both the `prod` and `staging` DBs.

- [ ] Use column E of [this spreadsheet](https://docs.google.com/spreadsheets/d/1gLKKDOGYde2WzlFTcCSHrQcYuLwdAvTCk8tQ6LjjdOY/edit#gid=0) to drop columns on the Unit and PrimaryPerson tables that are NOT included in the Public Extract of CRIS.

Going to update the name of this issue and create a separate issue for updating the ETL since we can postpone that task.

**Comment by sergiogcx** [comment]
This has now been done for both staging and production databases.
