### ISSUE TITLE
VZE: Locations details page add list of related crashes

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#178]
Would be good if this list could included clickable links to the related Crash details pages. (This could also be implemented using the existing Crash Index with search parameters but that might not be the cleanest UX)

Would also be good to have counts and summary stats of crashes at a location. Injury/fatality totals by mode, manner of collision, etc.

**Comment by sergiogcx** [comment]
You may want to check this page for testing:
https://localhost:3000/#/locations/5554229

**Comment by sergiogcx** [comment]
PR:
https://github.com/cityofaustin/atd-vz-data/pull/188

**Comment by sergiogcx** [comment]
Merged to master, closing.
