### ISSUE TITLE
ETL: CRIS data

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#18]
Automate the import process for CRIS data extracts. This isn't necessary to have a working system but we know APD has scripts that do this on a cron. This would replace the need to manually load data like we plan to at first in #17.

**Comment by sergiogcx** [comment]
We have been able to test the automated request process, forwarding the emails from Mateo's email to AWS, storing the emails in S3 and processing them. We will need to open new issues to plan around associating locations to crashes.
