### ISSUE TITLE
VZE: List of QA Tables to implement by priority

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#180]
We discussed adding a table for each of these crash record types sorted by priority. These could be toggled via a dropdown or filter buttons.

1. QA Deaths
2. QA Serious Injuries
3. QA all other injury

**Comment by sergiogcx** [comment]
This is the PR:
https://github.com/cityofaustin/atd-vz-data/pull/186

**Comment by sergiogcx** [comment]
Merged to master, closing.
