### ISSUE TITLE
ETL: Publish crash data to ArcGIS Online (AGOL)

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#19]

**Comment by sergiogcx** [comment]
It would be nice to run this process in multi-threaded fashion; we need to determine if there is an easy way to upsert or update each individual record. Perhaps we can use the crash_id field as the unique identifier.

**Comment by JaceDeloney** [comment]
This needs to be scoped a bit more. Need to determine how this would be useful to GIS users.
