### ISSUE TITLE
VZD: Drawing tool for Location boundaries

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#195]
_Idea from John we need to flesh out and prioritize_

- Functionality for version control and street name standardization
- Same pattern as the crash change log table
- Look into rerunning crash-to-location association query when polygon is updated

**Comment by sergiogcx** [comment]
@mateoclarke Street name standardization should be implemented in the front end in my opinion, that would allow the user to know and how to correct before it ever makes it into the database?

**Comment by sergiogcx** [comment]
Version control will require a migrations tool, I can look into that tomorrow:

https://sqitch.org/
http://www.liquibase.org/

**Comment by mateoclarke** [comment]
By database version control, I think @johnclary just meant the same changelog pattern as we are doing for the Crashes table.

For the Location name standardization, we already have another issue created for that:
https://github.com/cityofaustin/atd-vz-data/issues/176

**Comment by sergiogcx** [comment]
All the issues under this epic have been finished and implemented, leaving open for review.

**Comment by sergiogcx** [comment]
Closing, all the tasks here have been complete.
