### ISSUE TITLE
VZD: Standardize input of the name attributes for addresses on Locations Index/Details

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#196]
From @johnclary:

> besides the intersection geometry, we need to standardize input of the name attributes. in data tracker, we grab all this:
> - Primary St
> - Cross St
> - Landmark
> 
> Primary St and Cross St are controlled fields, restricted to valid values in the city’s official street segment layer (we could autocomplete them in VZE with a CORS request to the feature layer) and Landmark can be anything (another cross street name, or something like “Walmart Driveway”. it is not controlled entry and then the location name is concatenated as {Primary St} / {Cross St} ({Landmark})

**Comment by amenity** [comment]
@johnclary we need clarification: Does this standardization apply to a Crash or a Location...or both? Is the standardization happening on the front end editing side or the database validation side...or both?

**Comment by johnclary** [comment]
I was only considering this for the Locations records.

It would be ideal for crashes as well (e.g., to query all crashes on the same street, we would want them to be consistently named). The crashes already have address columns of varying quality, so this would be, like the way we're handing lat/lon, a way to supersede the values from CRIS/geocoding?

It occurs to me that we may also want address fields to capture the block range (for mid-block locations/crashes).

**Comment by sergiogcx** [comment]
The entire canonical database of streets (from ESRI) has been imported into postgres. We now need to find out how we are going to implement this into edit location.

**Comment by sergiogcx** [comment]
The next steps are located in #94
