### ISSUE TITLE
VZE: Research drawing tool for Location boundaries

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-vz-data#198]
Location definitions are fluid, so the editor will need an interface to edit the polygon for each location. 

Corresponding database work  in #195 will handle version control and street name standardization.

**Comment by mddilley** [comment]
#### Using uber/react-map-gl
https://github.com/uber/nebula.gl
https://github.com/uber/nebula.gl/tree/master/modules/react-map-gl-draw

#### Using alex3165/react-mapbox-gl
https://github.com/amaurymartiny/react-mapbox-gl-draw
https://github.com/alex3165/react-mapbox-gl

#### Using urbica/react-map-gl
https://urbica.github.io/react-map-gl-draw/
https://github.com/urbica/react-map-gl

#### Other resources
https://medium.com/@anujsingh_wd/custom-draw-on-map-mapbox-gl-js-mapbox-draw-gl-turf-js-react-js-af579bdaa05f
