### ISSUE TITLE
VZD: Push crash data to Socrata

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-vz-data#199]
- Crash table
- Persons table - this will allow us to calculate years of life lost

Potential use Python client helpers.
- socratautil
- https://github.com/xmunoz/sodapy

> before you can upsert data to a Socrata dataset, you need to specify a “row ID” in the dataset metdata. Docs: https://dev.socrata.com/docs/row-identifiers.html

**Comment by tcwcodes** [comment]
Hasura query for relevant Person/Primary Person data with crash dates:

```
query PersonPrimaryPersonByCrashDate {
  atd_txdot_person(where: {_or: [{prsn_injry_sev_id: {_eq: 1}}, {prsn_injry_sev_id: {_eq: 4}}]}) {
    prsn_injry_sev_id
    prsn_age
    prsn_gndr_id
    crash {
      crash_date
    }
  }
  atd_txdot_primaryperson(where: {_or: [{prsn_injry_sev_id: {_eq: 1}}, {prsn_injry_sev_id: {_eq: 4}}]}) {
    prsn_injry_sev_id
    prsn_age
    prsn_gndr_id
    drvr_zip
    crash {
      crash_date
    }
  }
}
```

**Comment by mddilley** [comment]
GraphQL query for current crash data columns published to Socrata.

```
query getCrashesSocrata {
        atd_txdot_crashes (limit: 10) {
            crash_id
    		crash_fatal_fl
            crash_date
            crash_time
            case_id
            rpt_latitude
            rpt_longitude
            rpt_block_num
            rpt_street_pfx
            rpt_street_name
            rpt_street_sfx
            crash_speed_limit
            road_constr_zone_fl
            latitude
            longitude
            street_name
            street_nbr
            street_name_2
            street_nbr_2
            crash_sev_id
            sus_serious_injry_cnt
            nonincap_injry_cnt
            poss_injry_cnt
            non_injry_cnt
            unkn_injry_cnt
            tot_injry_cnt
            death_cnt
        }
    } 
```

**Comment by sergiogcx** [comment]
@mddilley and I discussed that Both the persons table and primary person table have unique identifiers added a few months back, maybe those can be used to upsert both primary person and person tables.

Otherwise, it might be easier to just wipe out the entire database and re-upload everything every night :)

**Comment by JaceDeloney** [comment]
We discussed the potential to replace the database to facilitate a additional fields.
