### ISSUE TITLE
ETL: CR3

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#20]
Automate the attachment of CR3 PDFs to Crash records.

In the future we may want to extract out fields from the CR3, specifically Narrative and crash diagram fields.

- [ ] Explore options for automation of Brazos (Capybara or API)
- [ ] else: Automating retrieval of PDFs from G: network drive
- [ ] upload PDFs to S3 bucket and make database association on crash record ID
- [ ] OCR pdf/crop narrative & crash diagram sections

**Comment by amenity** [comment]
This lives in Brazos... not currently a priority. Need to discuss how we would automate data extraction from Brazos. Also concern that CR3s don't get updated in Brazos, so may conflict with CRIS data.

**Comment by sergiogcx** [comment]
@johnclary We are blocked on this until we can resolve the permissions for data access for our login.

**Comment by mateoclarke** [comment]
Progress from our Sprint Review #3...

We now know that CR3s for fatal crashes are stored here `G:\Trans\Transportation & Engineering\Transportation Safety\Fatalities`

We could write a retrieval program that gathers these (and maybe the APD internal memos) and copies them to S3 in the cloud. We could use this subset of `.pdf` &`.doc` files as a sample for attempting to automate the extract of narratives and crash diagrams.

We're also planning to request a dedicated Brazos login and programatic access to CR3s if APD is able to provide them. If not, Capybara? 🤷‍♂

**Comment by mateoclarke** [comment]
Discussed in a meeting with APD team, access should be forth coming. And potentially a new interface built out by the vendor to facilitate the automated data extraction without having to parse through the Brazos UI

**Comment by mateoclarke** [comment]
Updated credentials have been added to our pw manager. We should be good to explore what is possible for automated extraction with Capybara but the system is verrrrry slow so I'm not very optimistic about a bulk process. Officer Morgan has also put in an email to his Tyler Tech sales contact about creating an interface for us to have a better data retrieve pipeline. More soon...

**Comment by johnclary** [comment]
Just followed up w/ Officer Morgan about a Brazos contact for accessing cR3s programmatically. Our first request was on 9/19/19.
