### ISSUE TITLE
ETL: Implement record compare function

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-vz-data#213]
A record coming in from CRIS will need to be evaluated against a record from the database, both have to be the same format so they differences can be detected.

**Comment by sergiogcx** [comment]
This is a list of the fields I would consider important, let me know if there is one that needs to be added (or removed from this list):

```
crash_fatal_fl
crash_date
crash_time
case_id
rpt_latitude
rpt_longitude
rpt_hwy_num
rpt_block_num
rpt_street_name
rpt_sec_hwy_num
rpt_sec_block_num
rpt_sec_street_name
city_id
latitude
longitude
street_name
street_nbr
```

**Comment by JaceDeloney** [comment]
We will send this list over to Lewis and Team to confirm/add fields needed to flag.

**Comment by sergiogcx** [comment]
@JaceDeloney I've just made some updates based on the conversation we had earlier today, they are not in any specific order (since the order does not matter), and it is no problem at all modifying this list.

**Comment by sergiogcx** [comment]
The insertions are happening in development, I feel like this is too much of a novelty that will require several iterations, so after some thinking I resolved that an environment variable is needed to control whether we want that feature enabled or otherwise.
