### ISSUE TITLE
VZ(X): Build Local/Cloud Dev Environment

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-vz-data#216]
We will need a local dev environment, we just need to be able to:

- [x] Run a copy of the database
- [x] Run Hasura, and make sure the permissions/relationships are accurate.

**Comment by sergiogcx** [comment]
VZD RDS (Postgres): atd_vz_data_staging (schema)
VZD Staging:
https://vzd-staging.austintexas.io/console

**Comment by mateoclarke** [comment]
@sergiogcx Should we update our branches to have a `prod`, `staging`, and feature branches workflow now? And update our default branch to be `staging` with updated environment variables in VZE so we point at this DB/Hasura server instance in our local dev?

**Comment by mateoclarke** [comment]
Also, could you update the READMEs to explain our prod vs staging setups once thats ready?
