### ISSUE TITLE
VZV: evaluate forkability of NYC VZV

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#22]
Evaluate the forkability of NYC DOT's Vision Zero Viewer application for use with our data:
- https://github.com/nycdot/Vision_Zero_View/
- http://www.vzv.nyc/

- This will require understanding their AGOL usage and what layers and attributes we may need to define and create in AGOL.

**Comment by mateoclarke** [comment]
Today we started poking around to try to understand the shape of the data they are pulling out of arcgis and we discovered this ArcGIS REST Services Directory:
http://www.vzv.nyc:6080/arcgis/rest/services/Vision_Zero

Its still confusing. As one example we're trying to understand where the data for the crash point lives.

**Comment by johnclary** [comment]
interesting. 

so they have [map layers](http://www.vzv.nyc:6080/arcgis/rest/services/Vision_Zero/all_monthly_Injuries_and_fatalities/MapServer) for every year/month.

and [each layer](http://www.vzv.nyc:6080/arcgis/rest/services/Vision_Zero/bikeFatalities_and_Injuries_monthly/MapServer/249
) contains the injury points, apparently aggregated to intersections.

For example, [here's some of the point data](http://www.vzv.nyc:6080/arcgis/rest/services/Vision_Zero/bikeFatalities_and_Injuries_monthly/MapServer/249/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=html).

You can see that the layer has columns for each mode type aggregated by  time of day. E.g., `Bike_12_15` would be bike crashes from 12pm-3pm.

**Comment by johnclary** [comment]
i understand why they did this, but we could probably get by with a single map layer, or possibly one for each mode. and possibly just aggregate on the fly like we've done for dockless. i know we have performance issues with our dockless endpoint, but that's millions of rows, vs thousands here.

**Comment by johnclary** [comment]
the more i use this, the more i wonder how useful it is. e.g., i want to see the most dangerous places for bikes, but this map doesn't do that very well. need to do some testing and defining of uses cases with stakeholders

**Comment by mateoclarke** [comment]
In our architecture discussion last Thursday, we decided there is too much involved with the esri setup for the NYC data structure for us to do a 1:1 fork. 

Our next step is to identify/inventory the components of the VZV NYC site and use their design as a template. https://github.com/cityofaustin/atd-vz-data/issues/23

We'll get feedback from the Vision Zero team in our meeting of 7/31 on which components we need to prioritize for implementation.
