### ISSUE TITLE
VZE: Staging Environment (Netlify)

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-vz-data#229]
We need to be able to switch environment variables between staging and production. I tried in branch `216-sg-devenv` but I am struggling to determine why it runs locally but not on netlify. Let's fix this on this sprint.

https://app.netlify.com/sites/vze-staging/deploys

**Comment by sergiogcx** [comment]
The PR is up and ready for review:
https://github.com/cityofaustin/atd-vz-data/pull/249

**Comment by amenity** [comment]
Separate branches in repo and update Readme.

**Comment by sergiogcx** [comment]
Merged to master, closing.
