### ISSUE TITLE
VZV: inventory NYC pages/components

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#23]
If we are able to fork the VZV.NYC code, we need to evaluate which parts of the code base are relevant to us given our available data.

For example, they include data about things like signal interventions which we aren't yet tracking.

Go through NYC VZV and identify individual components. Sets the groundwork for a discussion about utility and priority of each one for our implementation.

**Comment by mddilley** [comment]
I created a Google form and sheet to track discussion around priority of components as we work through this project.
https://docs.google.com/forms/d/1OMFvtDCcaIxWJvFDsdrFFq9kc1t5LBRoo8S6bluleZ4/
https://docs.google.com/spreadsheets/d/1KYN4wU0DAsBA2QXATEHk9F_lwnuZNMentWahztP1jZQ/

**Comment by mddilley** [comment]
Converted the Google form to a doc to help the discussion on where to start and where to go or not go.
https://docs.google.com/document/d/1VrTtb8NrNi1v5c8oVp1_HZrmAK92yfAqGO_ATz9at40/edit#heading=h.cerbnwcigaib

**Comment by mateoclarke** [comment]
Nice, going to go ahead and close this one out since we have that doc in our project folder. Going to link to it in this issue for us to come back to as we scope out features:
https://github.com/cityofaustin/atd-vz-data/issues/82
