### ISSUE TITLE
VZE: Unify Crash table on one page (consolidate QA crash table)

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#230]
- [x] Update the columns in the table on `/crashes` to match the one on `/crashes/qa`. 
- [x] Delete `/crashes/qa` page
- [x] Drop "Unit Body Type" column
- [x] Update the navigation for just Crash link.

**Comment by sergiogcx** [comment]
PR:
https://github.com/cityofaustin/atd-vz-data/pull/264
