### ISSUE TITLE
VZD/E: Track "modified by" in Change log and in the Details section

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#234]

**Comment by sergiogcx** [comment]
PR:
https://github.com/cityofaustin/atd-vz-data/pull/261

**Comment by mateoclarke** [comment]
This requires a bit more testing, not working in staging currently.

**Comment by mateoclarke** [comment]
Also need to make sure this field gets added to the GET_ CRASH and UPDATE_CRASH queries and display it in the Details section
