### ISSUE TITLE
VZD/E: Need ability to modify fatality flag

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#236]
- [x] Add Two new columns to Crash DB Table: 
  - `apd_confirmed_fatality`
  - `apd_confirmed_death_count`
- [x] Add these fields as editable records on the Crash details page.
- [x] Update death count calculations to use `apd_confirmed_...` fields

**Comment by amenity** [comment]
@mateoclarke Clarify with Lewis: Do we also need columns for confirmed serious injuries?

**Comment by mateoclarke** [comment]
I've emailed Lewis for clarification about serious injuries

**Comment by sergiogcx** [comment]
I will also make sure that the comments on PR (https://github.com/cityofaustin/atd-vz-data/pull/264) are also accounted for in this issue.

**Comment by sergiogcx** [comment]
After thinking a little bit more about this, I am seeing the death_cnt is being used in quite a few different places, including comprehensive cost calculations, triggers, stored views, search filters... 

This will definitely turn into an epic.

**Comment by sergiogcx** [comment]
Inventory of all occurrences of `death_cnt`:

```
src/queries/crashes.js:19:death_cnt
src/queries/crashes.js:198:death_cnt
src/queries/CrashesQA.js:13:death_cnt
src/queries/CrashesQA.js:18:death_cnt
src/queries/CrashesQA.js:33:death_cnt
src/queries/Locations.js:35:death_cnt
src/queries/Locations.js:49:death_cnt
src/queries/dashboard.js:11:death_cnt
src/Components/TableWithFilters.js:219:death_cnt
src/views/Crashes/Crashes.js:54:death_cnt
src/views/Crashes/Crashes.js:92:death_cnt
src/views/Crashes/crashDataMap.js:272:death_cnt
src/views/Crashes/Crash.js:107:death_cnt
src/views/VZDashboard/VZDashboard.js:27:death_cnt
src/views/Locations/LocationCrashes.js:61:death_cnt
src/views/Locations/LocationCrashes.js:108:death_cnt
src/views/Locations/Location.js:121:death_cnt
```

In the database (both staging and prod):

Views:
view_location_injry_count_cost_summary (2)
view_location_injry_count_cost_summary (1)

Triggers:
atd_txdot_crashes_updates_audit_log (2)

**Comment by sergiogcx** [comment]
Ready for review, created a new issue for Locations page pulling death_cnt from primary person and person tables:

https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-vz-data/284

**Comment by mateoclarke** [comment]
@sergiogcx I don't think the second checkbox every got completed or at least pushed to master. The crash details page doesn't include these fields so I created #305 to cover it.
