### ISSUE TITLE
VZE: Add link to related Location record from Crash Details page

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#237]
maybe this is a feature of the map component. For now, simply a link to the associate Location Details page.

**Comment by sergiogcx** [comment]
PR:
https://github.com/cityofaustin/atd-vz-data/pull/269

![Screen Shot 2019-10-09 at 1.47.41 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/4a0b35dd-6b2d-44b0-a0fe-9946c178c531)

![Screen Shot 2019-10-09 at 1.48.30 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/3bc2a7dc-0d0d-4e8d-b442-4c0da42b7743)
