### ISSUE TITLE
VZD: How do we keep changes between `staging` and `prod` environments in sync?

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#238]
- DB schema changes
- SQL triggers
- views
- Hasura configuration (relationships, etc)
- software/dependency versions (ie: upgrades)
- more?

**Comment by amenity** [comment]
Document in README.

**Comment by sergiogcx** [comment]
While we can keep both data structures identical, it should also be noted that it isn't quite possible to keep both databases in perfect sync, the data will always be different one from the other.

Staging data should be seen more like dummy data, and we should try to keep it as close to the production data as possible.

Having said that, to manage the structure of the databases we can use a migration management tool such as:

https://alembic.sqlalchemy.org/en/latest/tutorial.html
https://sqitch.org/docs/manual/sqitchtutorial/

**Comment by mateoclarke** [comment]
documentation in repo README at a minimum for MVP

**Comment by mateoclarke** [comment]
## How to manually add columns to a table for VZD

### Postgres changes

1. On the staging database `atd_vz_data_staging`, make changes to your data structure either with a GUI (ex: TablePlus) or with SQL statements. 

2. Once you changes have been made, copy the SQL statement that modified the table to our [migration log](#) (TODO: make directory in repo) for version control.

- Ex: 

- ```sql
  ALTER TABLE "public"."atd_txdot_crashes" ADD COLUMN "micromobility_device_flag" varchar(1) NOT NULL DEFAULT 'N';
  ```

3. Execute the same SQL statement on the production database `atd_vz_data`

### Hasura changes

In the case of adding new database columns, you will need to update the permission in the Hasura UI to make new columns editable or available to the relevant permission groups.

4. In the vzd-staging Hasura site, go to the permissions page for the table you're editing
   - Ex: https://vzd-staging.austintexas.io/console/data/schema/public/tables/atd_txdot_crashes/permissions
5. Update which roles can select or update records.
6. Click the Settings gear icon in the top right corner of the Hasura page (or go to: https://vzd-staging.austintexas.io/console/settings/metadata-actions) and click "Export metadata" to get a son config from the staging environment.
7. Go to the production Hasura site on the equivalent Settings page (https://vzd.austintexas.io/console/settings/metadata-actions) and click "Import metadata". Select the file that was just exported from the staging site (ex: metadata.json)
8. Confirm that the permission you previously added to the staging site have been copied to production with your metadata import.

**Comment by sergiogcx** [comment]
PR for now:
https://github.com/cityofaustin/atd-vz-data/pull/298
