### ISSUE TITLE
VZD: Drop PII fields during ETL process

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#239]
Related to #166. Use column E of [this spreadsheet](https://docs.google.com/spreadsheets/d/1gLKKDOGYde2WzlFTcCSHrQcYuLwdAvTCk8tQ6LjjdOY/edit#gid=0) to exclude PII fields from data import

**Comment by sergiogcx** [comment]
This one is finished and merged to master, closing.
