### ISSUE TITLE
Map Requested Field Names to CRIS Extract

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-vz-data#24]
Email to Lewis on 6/4:

You’ve provided us with a list of fields (at the bottom of this email) that you’d like to include in the crash database. We need to map these fields to the field names that are in the CRIS extract. I’ve attached a complete listing of the fields in the public CRIS extract.

Is this something Frank could work on? He can just add a column on the attached XLSX and put the humanized field name from your list next to the corresponding field in the CRIS extract. Their may be a few fields that don’t map 1 to 1, or on present. That’s fine. Just note them and we’ll review

Case ID
Date
Time
Roadway system
Roadway part
Block number and all street info, including speed limit
Lat/Long
Unit description (this identifies the motor vehicle, pedestrian, cyclist, etc.)
Hit and Run
DL class
DL restriction
All Units - address (person)
All Units - Vehicle year, make, model
All Units - body style
All Units - injury severity
All Units - age, ethnicity, sex, restraint, alcohol/drug specimen, drug test result
Proof of liability
Contributing Factors – all which are captured in “Contributing” and “May have”
Crash severity
Injury severity
Intersection-relation type
Light condition
Railroad related flag
Road construction flag
Crash speed limit
Active School Zone
Road type
Highway system, number, and suffix for both primary and secondary
On system
School bus flag
Toll Road flag
Traffic control
Weather condition
Surface condition
DWI charge
Object struck
Helmet
Day of week
Month
Year
Collision
Unit group involved
Crash type
Fatality
PRSN_TYPE_ID

**Comment by amenity** [comment]
@johnclary or @mateoclarke - will you attach the spreadsheet to this and close this guy out? 
And if there are any follow up issues besides #14 - add them to the backlog?

**Comment by amenity** [comment]
& add an estimate. 👕🙏

**Comment by mateoclarke** [comment]
@johnclary attaching the .xls file that Joel worked on. Looks like they highlighted the field they want us to use from CRIS but there isn't a clean title case field label. We'd need to do that ourselves.

Is this ready to use in Knack or do we need to clean it up more?
