### ISSUE TITLE
VZE: Add a “comprehensive cost” summary for Crash Details

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#245]
UI for columns created in #148. 

- [x] new field on Crash details page

**Comment by johnclary** [comment]
@mateoclarke see comment from Lewis and make sure y'all have it straight :

> As we are about to apply comprehensive costs and start analyzing the data, I want to ensure that we are counting serious injuries as only the ones designated “A” or “suspected serious injury” or “incapacitating injury” on the CR3s.  I was looking at a few case IDs (180210757, 180131087) in the VZE that have serious injury counts that include both “incapacitating injuries” and “non-incapacitating injury.” I know there are various scales, so want to make sure we’ve been clear on our end of only including the second level of the table below as “serious”. It’d be okay to add up the IDs 2 and 3 as “other injuries.”

![Screen Shot 2019-10-07 at 1.41.01 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/52cee43c-6e48-4895-80b4-2713b0b6ba57)
