### ISSUE TITLE
ETL: Review BASH script that APD uses to automate CRIS data loading

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-vz-data#26]

**Comment by amenity** [comment]
This shouldn't be a blocker; we probably won't use it. But it will be informative.

**Comment by mateoclarke** [comment]
Sent @sergiogcx and @johnclary a zipped sample of the APD extract via email. Reaching out to AK about Bash script now...

**Comment by sergiogcx** [comment]
Thanks for sharing the data, this is going to be helpful to begin implementing ETL tables.

Also looking forward to the bash script (if available)

**Comment by mateoclarke** [comment]
Just sent the zipped bash files via email too. Going to leave it to you @sergiogcx to review. Feel free to comment/close this issue out once you've had a chance to pull out any insights.

**Comment by mateoclarke** [comment]
This is back alive in issue #329
