### ISSUE TITLE
GIS: Create canonical intersection layer on ArcGIS Online

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-vz-data#27]
Daniel Y will provide a copy. Need to talk to Jaime M as well; she has recently been working with this data. 

Once we have the layer we need to load it to ArcGIS online and figure out how it will be versioned and backed up.

**Comment by TracyLinder** [comment]
### 9/5/19 Note:

During backlog grooming today, this was moved from New Issues to Needs Scoping, and John & Jaime were assigned. Please correct as needed. (New Issues does not seem the appropriate pipeline for this issue.)

**Comment by johnclary** [comment]
I will discuss w/ Lewis and prioritize.
