### ISSUE TITLE
Bug: VZE: Crash details total count vs serious injuries count

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-vz-data#271]
Lewis reported an issue with the Crash details page, it appears the total serious count of injuries mismatches the database count:

![Screen Shot 2019-10-10 at 10.36.23 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/99ec37c8-db5e-455e-9c2e-d126045d164f)

![Screen Shot 2019-10-10 at 10.36.16 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/bfe815d7-f824-42d6-877a-b1850ba73dfa)

**Comment by mateoclarke** [comment]
I'll take this one. Working in the Crash page right now. We must we using total injury count instead.
