### ISSUE TITLE
Signal Projects dashboard modal displays "NaN" under "Updated" field

### ISSUE THREAD

**Issue by tcwcodes** [cityofaustin/atd-vz-data#275]
https://transportation.austintexas.io/signal-projects/

**Comment by mateoclarke** [comment]
@tcwcodes I think you added this issue to the wrong repo. Can you move it to https://github.com/cityofaustin/transportation.austintexas.io

**Comment by tcwcodes** [comment]
You're right, I must have left it under the default branch by accident. Moving it now, thanks for the heads up!

**Comment by tcwcodes** [comment]
> @tcwcodes I think you added this issue to the wrong repo. Can you move it to https://github.com/cityofaustin/transportation.austintexas.io

You're right, I must have left it under the default branch by accident. Moving it now, thanks for the heads up!

**Comment by tcwcodes** [comment]
Issue moved to [cityofaustin/transportation.austintexas.io #327](https://github.com/cityofaustin/transportation.austintexas.io/issues/327) via [**ZenHub**](https://www.zenhub.com/)
