### ISSUE TITLE
ETL: Associate crashes with locations

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-vz-data#28]
_From comment below:_

All though we have the relationships setup in Knack for this, the ETL need here is to associate a crash record (a point) with a discrete, pre-defined location (a polygon) using spatial processing. This process would locate the record ID of any overlapping location, and set the Knack record link accordingly.

We can use the atd-agol-util for this.

We first need to define those location records/geometries. Will open a separate issue.

**Comment by mateoclarke** [comment]
@johnclary, @sergiogcx and I were under the impression that this task was about creating a new connection in Knack between the Crashes and Locations table but that appears to already have been created.

[Screen Shot 2019-07-05 at 2.43.07 PM.png](https://images.zenhubusercontent.com/59f0b24ba468affe6df81d8f/b08d6d2b-9c5e-4d96-bbb5-088a7c42cab9)

Is there more work to do here? Should it be closed? May we get a description above for the task?!

**Comment by johnclary** [comment]
@mateoclarke yes, let me update this and related issues with what work's been done in knack.

**Comment by johnclary** [comment]
The need here is to associate a crash record (a point) with a discrete, pre-defined location (a polygon) using spatial processing. This process would locate the record ID of any overlapping location, and set the Knack record link accordingly.

We can use the [`atd-agol-util`](https://github.com/cityofaustin/atd-data-utilities/blob/master/atd-agol-util/agolutil/agolutil.py) for this.

We first need to define those location records/geometries. Will open a separate issue.

**Comment by sergiogcx** [comment]
After speaking with Mateo, it looks like creating the locations table will take time to digest and come up with a good solution to populate data into them.  I will need to read into esri/arcGIS/PostGIS to prepare and touch base with you all.

**Comment by sergiogcx** [comment]
Detaching from sprint 3 until there is more clarity.

**Comment by johnclary** [comment]
@sergiogcx we have a polygon endpoint for matching crash points to locations:
https://services.arcgis.com/0L95CJ0VTaxqcmED/ArcGIS/rest/services/Intersection_Polygons_Test/FeatureServer/0

**Comment by sergiogcx** [comment]
Closing, we are now able to associating a location to a crash:

![Screen_Shot_2019-08-27_at_4_36_31_PM.jpg](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/34a92360-8718-4ebd-a1b3-58f116af6acb)
