### ISSUE TITLE
ETL: Automating and Deploying CRIS ETL

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#286]
- Merging data across multiple csv files
- Importing data into both databases
- Reimplementing the scripts based on database changes
- ~Reimplementing the pipeline (assuming we have access to pull data from an SFTP server instead of using Capybara)~ access to pull data from SFTP will be delayed indefinitely until TxDOT implements what they currently do for APD.

**Comment by sergiogcx** [comment]
The entire pipeline is now working in staging, production will be running its first test run tonight. If more troubleshooting is needed, new issues will need to be created to fix any problems.
