### ISSUE TITLE
VZE: Person/Primary Person sus_serious_injury_count

### ISSUE THREAD

**Issue by tcwcodes** [cityofaustin/atd-vz-data#293]
Similar to <a href="https://github.com/cityofaustin/atd-vz-data/issues/284">#284</a>. In "views/Locations/Location.js", <a href="https://github.com/cityofaustin/atd-vz-data/blob/f65a9a20af095d6a6fccee9568a1f2a2e5b7ee47/atd-vze/src/views/Locations/Location.js#L145">this line of code</a> aggregates "sus_serious_injry_cnt" in the Person and Primary Person tables, but I saw that there is a "sus_serious_injry_cnt" field in the crash table, and I thought we might want to refer to that instead.

**Comment by mateoclarke** [comment]
@tcwcodes, not following you on the work that needs to happen here...

I did ⌘-F `sus_serious_injury_cnt`and don't find anything in the repo. Also, there is no "views/locations.js" file. Did you mean "views/Locations/Location.js"? 

Was this issue supposed to be resolved by one of your PRs?
https://github.com/cityofaustin/atd-vz-data/pull/292/files

Or maybe what you're describing was already resolved by @sergiogcx's PR?
https://github.com/cityofaustin/atd-vz-data/pull/283

Sorry for my confusion. Let's clarify the description and/or close this out if its not necessary anymore.

**Comment by tcwcodes** [comment]
Sorry about that! You're right, I meant "views/Locations/Location.js". I was referring to <a href="https://github.com/cityofaustin/atd-vz-data/blob/f65a9a20af095d6a6fccee9568a1f2a2e5b7ee47/atd-vze/src/views/Locations/Location.js#L145>this line of code</a>. It aggregates "sus_serious_injry_cnt" in the Person and Primary Person table, but I saw that there is an APD confirmed serious injury field in the crash table, and I thought we might want to refer to that instead. I created the issue to start the discussion on whether to go ahead with that.

**Comment by tcwcodes** [comment]
Correction, the field in the crash table is not "confirmed," so maybe it doesn't really make a difference.

**Comment by tcwcodes** [comment]
@mateoclarke Checking in to see if you think this is necessary (puling serious injury data from the crash table instead of aggregating from Person/Primary Person). If not, I'll close it out.

**Comment by mateoclarke** [comment]
Yeah, let's go ahead and use the Crash table for the aggregation since thats where the data will be updated over time. Good call.

**Comment by tcwcodes** [comment]
Going to close this issue out, as it is already being addressed in a <a href="https://github.com/cityofaustin/atd-vz-data/pull/325">PR</a> that @mddilley has submitted.
