### ISSUE TITLE
ETL: Data extraction strategy

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-vz-data#32]
We need to determine an overall strategy to extract data from CRIS' website.

**Comment by sergiogcx** [comment]
So far we have had success using Capybara to log in to the site automatically, now we need to test if the data can be requested through the javascript injections as implemented in another issue.

I will also explore changing the agent name in Capybara, to match the Chrome name and see if we can get rid of the error message. Also, I need to check if I can force the URL to the wizard.

**Comment by sergiogcx** [comment]
We have been able to close the circle and test the request and gathering of data automatically using Capybara, Amazon SES and S3.
