### ISSUE TITLE
Reconcile differences between VZD fatality totals vs what VZ Program staff have

### ISSUE THREAD

**Issue by tcwcodes** [cityofaustin/atd-vz-data#323]
@johnclary commented on [Wed Oct 16 2019](https://github.com/cityofaustin/atd-data-tech/issues/674)

VZD says there are 87 fatal crashes in Austin in 2019. Lewis reports that their list is ~60 fatalities. How do we account for that difference.

---

@mateoclarke commented on [Wed Oct 16 2019](https://github.com/cityofaustin/atd-data-tech/issues/674#issuecomment-542902132)

Lewis has emailed us all the case IDs for the year

---

@johnclary commented on [Wed Oct 16 2019](https://github.com/cityofaustin/atd-data-tech/issues/674#issuecomment-542902993)

here's the data from the email, with this note from Joel:

> Each row below represents a fatality rather than a fatal crash. You’ll see there are a few Case IDs with multiple fatalities, and one with no Case ID due to the fact that UTPD responded to it. So we’re actually up to 68 fatalities by our count.

```
year/case id/sequency/date
2019    190150158   #1  1/15/19
2019    190161105   #2  1/16/19
2019    190081623   #3  1/8/19
2019    190260086   #4  1/26/19
2019    UTPD    n/a 1/29/19
2019    190320079   #5  2/1/19
2019    190370320   #6  2/6/19
2019    190400694   #7  2/9/19
2019    190521569   #8  2/21/19
2019    190521894   #9  2/21/19
2019    190581824   #10 2/27/19
2019    190871796   #11 3/28/19
2019    190881844   #12 3/29/19
2019    190761827   #13 3/17/19
2019    190800389   #14 3/21/19
2019    190921776   #15 4/2/19
2019    190921776   #15 4/2/19
2019    190961200   #16 4/6/19
2019    190930132   #17 4/3/19
2019    191070052   #18 4/17/19
2019    191070614   #19 4/17/19
2019    191080319   #20 4/18/19
2019    191080673   #21 4/18/19
2019    191110655   #22 4/21/19
2019    191040737   #23 4/14/19
2019    191161832   #24 4/26/19
2019    191220286   #25 5/2/19
2019    191270134   #26 5/7/19
2019    191320369   #27 5/12/19
2019    191320666   #28 5/12/19
2019    191321936   #29 5/12/19
2019    191380171   #30 5/18/19
2019    191381928   #31 5/18/19
2019    191390962   #32 5/19/19
2019    191521857   #33 6/1/19
2019    191530277   #34 6/2/19
2019    191540252   #35 6/3/19
2019    191590874   #36 6/8/19
2019    191611200   #37 6/10/19
2019    191801699   #38 6/29/19
2019    191880028   #39 7/7/19
2019    191950368   #40 7/14/19
2019    192031962   #41 7/22/19
2019    192050100   #42 7/24/19
2019    192080141   #43 7/27/19
2019    192090230   #44 7/28/19
2019    192061923   #45 7/25/19
2019    192160076   #46 8/4/19
2019    192191570   #47 8/7/19
2019    192241378   #48 8/14/19
2019    192280292   #49 8/16/19
2019    192291933   #50 8/17/19
2019    192291933   #50 8/17/19
2019    192311712   #51 8/19/19
2019    192351073   #52 8/23/19
2019    192440191   #53 9/1/19
2019    192440444   #54 9/1/19
2019    192450248   #55 9/2/19
2019    192500231   #56 9/7/19
2019    192540094   #57 9/11/19
2019    192540190   #58 9/11/19
2019    192560573   #59 9/13/19
2019    192661710   #60 9/23/19
2019    192700846   #61 9/27/19
2019    19-2711895  #62 9/28/19
2019    192732043   #63 9/30/19
2019    192761969   #64 10/3/19
2019    192650413   #65 9/22/19
```

---

@tcwcodes commented on [Wed Oct 16 2019](https://github.com/cityofaustin/atd-data-tech/issues/674#issuecomment-542905129)

Going to move this to atd-vz-data and reapply labels.

**Comment by tcwcodes** [comment]
Submitted a PR that adds the City of Austin filter for "apd_confirmed_death_count." Brings us much closer to the correct Fatalities YTD.

**Comment by tcwcodes** [comment]
Merged PR. Should fix the problem, but didn't set the PR to close this issue since it seemed like we may need to do some manual data scrubbing to ensure the numbers align perfectly (I think Lewis was saying there was still a difference of 1).

**Comment by mateoclarke** [comment]
Let's do a manual diff against these Case IDs in VZD as soon as we can.

**Comment by mateoclarke** [comment]
Providing an updated on behalf of @tcwcodes. We have a spreadsheet that matches the crash records we have available in our database against the list of fatalities that the VZ manages with APD.

|#   |Lewis - Case ID|TxDOT - Case ID|TxDOT - Date|Comments                                                |
|----|---------------|---------------|------------|--------------------------------------------------------|
|1   |190150158      |190150158      |1/15/19     |Match                                                   |
|2   |190161105      |190161105      |1/16/19     |Match                                                   |
|4   |190260086      |190260086      |1/26/19     |Match                                                   |
|n/a |               |1901194        |1/28/19     |UTPD bike fatality                                      |
|3   |190081623      |190081623      |1/8/19      |Match                                                   |
|5   |190320079      |190320079      |2/1/19      |Match                                                   |
|8   |190521569      |190521569      |2/21/19     |Match                                                   |
|9   |190521894      |190521894      |2/21/19     |Match                                                   |
|10  |190581824      |190581824      |2/27/19     |Match                                                   |
|6   |190370320      |190370320      |2/6/19      |Match                                                   |
|7   |190400694      |190400694      |2/9/19      |Match                                                   |
|13  |190761827      |190761827      |3/17/19     |Match                                                   |
|14  |190800389      |190800389      |3/21/19     |Match                                                   |
|11  |190871796      |190871796      |3/28/19     |Match                                                   |
|12  |190881844      |19881844       |3/29/19     |Case ID was one digit off (human error?) in VZ team list|
|23  |191040737      |191040737      |4/14/19     |Match                                                   |
|18  |191070052      |191070052      |4/17/19     |Match                                                   |
|19  |191070614      |191070614      |4/17/19     |Match                                                   |
|20  |191080319      |191080319      |4/18/19     |Match                                                   |
|21  |191080673      |191080673      |4/18/19     |Match                                                   |
|15  |190921776      |190921776      |4/2/19      |Match                                                   |
|15  |190921776      |190921776      |4/2/19      |Match                                                   |
|22  |191110655      |191110655      |4/21/19     |Match                                                   |
|24  |191161832      |191161832      |4/26/19     |Match                                                   |
|17  |190930132      |190930132      |4/3/19      |Marked as non-fatal in CRIS                             |
|16  |190961200      |190961200      |4/6/19      |Match                                                   |
|27  |191320369      |191320369      |5/12/19     |Match                                                   |
|28  |191320666      |191320666      |5/12/19     |Match                                                   |
|29  |191321936      |191321936      |5/12/19     |Match                                                   |
|30  |191380171      |191380171      |5/18/19     |Match                                                   |
|31  |191381928      |191381928      |5/18/19     |Match                                                   |
|32  |191390962      |191390962      |5/19/19     |Match                                                   |
|25  |191220286      |191220286      |5/2/19      |Match                                                   |
|?   |               |191230338      |5/3/19      |Missing from VZ team list                               |
|26  |191270134      |191270134      |5/7/19      |Match                                                   |
|33  |191521857      |191521857      |6/1/19      |Match                                                   |
|37  |191611200      |191611200      |6/10/19     |Match                                                   |
|34  |191530277      |191530277      |6/2/19      |Match                                                   |
|38  |191801699      |191801699      |6/29/19     |Match                                                   |
|35  |191540252      |191540252      |6/3/19      |Match                                                   |
|36  |191590874      |191590874      |6/8/19      |Match                                                   |
|39 |191880028      |7/7/19         |            |Not downloaded from CRIS yet                            |
|40 |191950368      |7/14/19        |            |Not downloaded from CRIS yet                            |
|41 |192031962      |7/22/19        |            |Not downloaded from CRIS yet                            |
|42 |192050100      |7/24/19        |            |Not downloaded from CRIS yet                            |
|43 |192080141      |7/27/19        |            |Not downloaded from CRIS yet                            |
|44 |192090230      |7/28/19        |            |Not downloaded from CRIS yet                            |
|45 |192061923      |7/25/19        |            |Not downloaded from CRIS yet                            |
|46 |192160076      |8/4/19         |            |Not downloaded from CRIS yet                            |
|47 |192191570      |8/7/19         |            |Not downloaded from CRIS yet                            |
|48 |192241378      |8/14/19        |            |Not downloaded from CRIS yet                            |
|49 |192280292      |8/16/19        |            |Not downloaded from CRIS yet                            |
|50 |192291933      |8/17/19        |            |Not downloaded from CRIS yet                            |
|50 |192291933      |8/17/19        |            |Not downloaded from CRIS yet                            |
|51 |192311712      |8/19/19        |            |Not downloaded from CRIS yet                            |
|52 |192351073      |8/23/19        |            |Not downloaded from CRIS yet                            |
|53 |192440191      |9/1/19         |            |Not downloaded from CRIS yet                            |
|54 |192440444      |9/1/19         |            |Not downloaded from CRIS yet                            |
|55 |192450248      |9/2/19         |            |Not downloaded from CRIS yet                            |
|56 |192500231      |9/7/19         |            |Not downloaded from CRIS yet                            |
|57 |192540094      |9/11/19        |            |Not downloaded from CRIS yet                            |
|58 |192540190      |9/11/19        |            |Not downloaded from CRIS yet                            |
|59 |192560573      |9/13/19        |            |Not downloaded from CRIS yet                            |
|60 |192661710      |9/23/19        |            |Not downloaded from CRIS yet                            |
|61 |192700846      |9/27/19        |            |Not downloaded from CRIS yet                            |
|62 |19-2711895     |9/28/19        |            |Not downloaded from CRIS yet                            |
|63 |192732043      |9/30/19        |            |Not downloaded from CRIS yet                            |
|64 |192761969      |10/3/19        |            |Not downloaded from CRIS yet                            |
|65 |192650413      |9/22/19        |            |Not downloaded from CRIS yet                            |

**Comment by mateoclarke** [comment]
@tcwcodes's SQL code used for the reporting:

```SQL
SELECT
	case_id,
	crash_date,
	apd_confirmed_death_count
FROM
	atd_txdot_crashes
WHERE
	city_id = 22
	AND crash_fatal_fl = 'Y'
	AND crash_date BETWEEN '2019-01-01' AND '2019-12-31'
```
