### ISSUE TITLE
ETL: Update APD bash script to get ATD extract

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#329]
We need to propose an update to APD's `load_crash_tables.sh` script. Alternatively, we could create our own new script without modifying APD, but there might be other hurdles to that in coordinating when the scripts run.

We need to:
- [x] identify how our extract name would be unique w/ Mark
- [x] work with CTM to create shared FTP user for atd-data on coa22 with access to TXDot root path and sibling folder.
- [x] make sure APD script has permissions to run on sibling folder

The script should:
- [x] make a sibling directory on SFTP
- [x] find our zip by filename 
- [x] copy zip to sibling folder
- [x] delete our zip from txdot user home path.

**Comment by sergiogcx** [comment]
This is the repo in which it currently exists:
https://gitlab.com/atd-datatech/atd-vz-data-sftp-extraction-shell

**Comment by sergiogcx** [comment]
We will need to discuss what the next steps are, specifically about deployment and testing. Will create new issues.

**Comment by mateoclarke** [comment]
https://github.com/cityofaustin/atd-vz-data/issues/354#issuecomment-549552695
