### ISSUE TITLE
VZE: Remove Sidebar?

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-vz-data#336]
For discussion: do we even need the sidebar? It takes up a 1/6th of the page width. E.g. can we move to a header row?

**Comment by mateoclarke** [comment]
I'd vote no because its more work than its worth.

You can easily collapse it to be smaller, see screenshot...

![Screen Shot 2019-10-22 at 2.03.54 AM.png](https://images.zenhubusercontent.com/59f0b24ba468affe6df81d8f/92d6e1c8-4407-4473-8b10-dc88ae554b2c)

**Comment by mateoclarke** [comment]
@johnclary Can we close this one?

**Comment by JaceDeloney** [comment]
@johnclary going to close this out. If you object, we can open it back up.
