### ISSUE TITLE
VZD: Incorporate "Blueform" Crashes

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-vz-data#351]
Blueform crashes are crashes which were not reported via CRIS, but are tracked by APD  for incidents w/ less than $1k in damage.

Lewis would  like to know the level of effort to import these crashes from spreadsheet  into the database. These records have a limited set of fields, basically address and date.

**Comment by johnclary** [comment]
@mateoclarke @sergiogcx @mddilley would y'all discuss and estimate level of effort? We need to get back to Lewis on an ETA if we were to prioritize this.

**Comment by sergiogcx** [comment]
Did Lewis say he had a dataset of about 100k records in excel/csv?

If so, we can add them quickly to the database and we can use the grid table component to quickly create an index page.

**Comment by johnclary** [comment]
Yes, I believe 100k is about right. @sergiogcx what do you think  about adding these to  the `crashes` table and adding a `source` column for `blueform`  or `cris`?

**Comment by sergiogcx** [comment]
It depends on how similar the blueform records are to the cris records. If they have the exact same format, it should be a straight forward process, we could just add a column that identifies the origin (1 = Cris, 2=Blueform, etc...).

If the records are very different, they will need to be transformed, or set up a separate table altogether if they are straight up incompatible.

We should also have ETL pipeline considerations for these blueform records, how often will they be added, how will they be included, etc.

**Comment by mateoclarke** [comment]
The Blueform records will need a similar trigger for economic cost and comprehensive costs estimations. One reason all in the same table might make sense. It is a much more basic column structure.

**Comment by sergiogcx** [comment]
Yea, let's look at the data structure, if it is simple enough we can transform it. I can start looking into adding another column and index.

**Comment by sergiogcx** [comment]
The records have been inserted in the database, all there is left is to implement functionality around it, also implement the UI. There is an issue for that: https://github.com/cityofaustin/atd-data-tech/issues/905
