### ISSUE TITLE
VZV: Publish data for Serious Injury + Fatal Crashes by Mode chart

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-vz-data#357]
The data for this chart is currently hard-coded with figures from the paper Vision Zero Dashboard released by the Vision Zero team (data up to 8/26/(18 & 19)).

Data about modes involved in crashes needs to be published to Socrata to populate this chart with data programatically.

### Chart
![Screen Shot 2019-10-28 at 12 16 40 PM](https://user-images.githubusercontent.com/37249039/67700904-dd906700-f97c-11e9-9307-d89339588b56.png)

**Comment by mateoclarke** [comment]
We need to flesh out more the data structure required. 

Could we include mode as a column in the new Persons table and aggregate these numbers based on number of people? Or does it have to be by crash?

**Comment by mddilley** [comment]
I've been looking into this more, and I see that a single unit is associated to a person in the `atd_txdot_person` table, but, when pulling records from the `atd_txdot_primaryperson` table, only `unit_nbr` is available. Need to find out if there is overlap in people represented in these two tables to avoid duplicate records.

When pulling crashes records, multiple modes can be involved in a single crash. In VZE, we iterated through the arrays of unit objects to increment totals by type (one crash involving two motor vehicles would add 2 to the motor vehicles total). This would require some additional steps, but we could add these totals as columns to each crash row in the script and then upsert in Socrata (ex. MOTOR VEHICLES: 2, PEDESTRIAN: 1, ...).

**Comment by mateoclarke** [comment]
@mddilley yeah for this specific visualization, I think we'd want to pull out an array of modes in a new column for the public crashes table. Probably also for contributing factors too. I think we could do something like:

```graphql

  atd_txdot_crashes(limit: 100){
    units {
      contrib_factr_p1_id
      contrib_factr_p2_id
      body_style {
        veh_body_styl_desc
      }
      unit_description {
        veh_unit_desc_desc
      }
    }
  }
```

Example response with >1 units:
```graphql
      {
        "units": [
          {
            "contrib_factr_p1_id": 3,
            "contrib_factr_p2_id": 1,
            "body_style": {
              "veh_body_styl_desc": "PASSENGER CAR, 4-DOOR"
            },
            "unit_description": {
              "veh_unit_desc_desc": "MOTOR VEHICLE"
            }
          },
          {
            "contrib_factr_p1_id": 5,
            "contrib_factr_p2_id": 1,
            "body_style": {
              "veh_body_styl_desc": "BUS"
            },
            "unit_description": {
              "veh_unit_desc_desc": "MOTOR VEHICLE"
            }
          },
          {
            "contrib_factr_p1_id": 9,
            "contrib_factr_p2_id": 2,
            "body_style": null,
            "unit_description": {
              "veh_unit_desc_desc": "PEDESTRIAN"
            }
          }
        ]
      },
```

And then write the Python code to parse the data into columns and push the values as an array or probably just plaintext comma separated values.  

@johnclary do we have examples of one-to-many columns in other places in our open data? Is there a best pattern? @sergiogcx any suggestions for the Python relationship munging? Doesn't seem like array or objects are supported value types:
https://support.socrata.com/hc/en-us/articles/202949918-Importing-Data-Types-and-You-

**Comment by mateoclarke** [comment]
Also thinking out loud, maybe we want to capture at the crash level if the crash record is pedestrian-involved, bicycle-involved, motorcycle-involved or only between motor vehicles as three broad categories with simple boolean flags.
