### ISSUE TITLE
VZV: Number of years of life lost viz

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#359]
monthly or yearly chart for years of life lost

**Comment by amenity** [comment]
Discussed making very basic data set that would be a by-month summary of injuries and fatalities available in Socrata. 

This would include:
 - Age
 - Gender 
 - Driver zip
 - Date

TBD weather we should include:
 - Ethnicity
 - Driver city - less detailed than zip 
 - Unit - where the owner of the unit is
 - Crash ID

@johnclary is going to talk to Elaine N. at CTM to see about legal privacy implications of that second set.

**Comment by amenity** [comment]
This won't be updating until #199 is done, but static visualization is great.

**Comment by tcwcodes** [comment]
Hasura query:

query PersonPrimaryPersonByCrashDate {
  atd_txdot_person(where: {_or: [{prsn_injry_sev_id: {_eq: 1}}, {prsn_injry_sev_id: {_eq: 4}}]}) {
    prsn_injry_sev_id
    prsn_age
    prsn_gndr_id
    crash {
      crash_date
    }
  }
  atd_txdot_primaryperson(where: {_or: [{prsn_injry_sev_id: {_eq: 1}}, {prsn_injry_sev_id: {_eq: 4}}]}) {
    prsn_injry_sev_id
    prsn_age
    prsn_gndr_id
    drvr_zip
    crash {
      crash_date
    }
  }
}

**Comment by JaceDeloney** [comment]
hey @johnclary Did we ever get clarification from CTM on any privacy concerns that they may have as it relates to the following dataset:
- Ethnicity
- Driver city - less detailed than zip
- Unit - where the owner of the unit is
- Crash ID
