### ISSUE TITLE
VZV: contributing factors viz

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#360]
A graph showing the most common contributing factors for the past year of data.

Could be similar to the manner of collisions graph on the Locations Details page.

![Screen Shot 2019-11-05 at 6.59.19 PM.png](https://images.zenhubusercontent.com/59f0b24ba468affe6df81d8f/dc9d6a5b-a3ed-426d-abea-0fea6afda9bb)

**Comment by JaceDeloney** [comment]
Tracking in #511
