### ISSUE TITLE
VZV: Monthly/ YTD fatal crash counts

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#362]
- [ ] calculate the % change in fatal crashes YTD versus "this time last year"

![Screen Shot 2019-10-28 at 3 34 56 PM](https://user-images.githubusercontent.com/5697474/67715793-84363100-f998-11e9-8241-8dbcbb0fbba9.png)

**Comment by JaceDeloney** [comment]
Closing this out as it has been completed in #454
