### ISSUE TITLE
VZV: Traffic fatalities by mode

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#363]
![Screen Shot 2019-10-28 at 3 36 57 PM](https://user-images.githubusercontent.com/5697474/67715960-d6775200-f998-11e9-8524-329f12ac78ca.png)

**Comment by JaceDeloney** [comment]
Using a bar chart, show traffic fatalities by mode for the years of data that are available in the database. The following modes should be displayed: Pedestrian (should include e-scotters), Motor Vehicle, Motorcycle, Bicycle. The modes should be stacked with the mode with the most deaths at the bottom and the mode with the least deaths at the top.

![Screen Shot 2019-12-09 at 9.11.43 AM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/ef93fd45-2da6-490e-b56f-1b75a377e872)

The user should be able to hover over or tap the components of the bar chart to see more specific information. The information included in the "hover box" should include year, mode, and number of fatalities.

![Screen Shot 2019-12-09 at 9.12.45 AM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/d8bab8cc-7ec2-4445-a9e3-cc09d64a902c)

There should be a disclaimer below the chart outlining the latest date that we have data for. Example below.

![Screen Shot 2019-12-09 at 9.21.35 AM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/0e3b171f-1557-4477-ac59-98b1c0d1cd15)

You can find an example of this type of chart in the SFGov Traffic Fatalities portal here: https://sfgov.org/scorecards/transportation/traffic-fatalities

**Comment by JaceDeloney** [comment]
@mddilley do you mind assigning an estimate to this?
