### ISSUE TITLE
VZV: Time of Day/Day of Week viz

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#364]
Killed and Seriously injured 

![Screen Shot 2019-10-28 at 3 38 10 PM](https://user-images.githubusercontent.com/5697474/67716046-07578700-f999-11e9-90f0-3e9eed73d63b.png)

![Screen Shot 2019-10-28 at 3 40 08 PM](https://user-images.githubusercontent.com/5697474/67716187-5a313e80-f999-11e9-927f-6cc12cac9cfd.png)

**Comment by JaceDeloney** [comment]
@mateoclarke do you remember where you got these screenshots from? I'm interested in viewing the source doc

**Comment by JaceDeloney** [comment]
This is being worked on in #505
