### ISSUE TITLE
VZD Question: 6th & Congress default location

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#378]
> Locations – 6th and Congress pops up as the highest crash injury costs and most total crashes but many of the addresses are for other crash locations.  I assume this is b/c it is the default location for no X/Ys, right?

**Comment by mateoclarke** [comment]
We're noticing that for values that have been geocoded by Here that are associated to the 6th & Congress location, all the ones I've looked through plot to the same exact coordinates:
Latitude: 30.26759
Longitude: -97.74299

Could it be that Here uses the address and finds that its in Austin and uses those coordinates as a default center of Austin?

**Comment by mateoclarke** [comment]
Using the [testing sandbox environment with Here](https://developer.here.com/api-explorer/rest/geocoder/latitude-longitude-intersection), we sent a geocode request with City = Austin the intersection information blank. It return the same coordinates as above confirming our theory that those coordinates are some kind of default for Austin.

<img width="998" alt="Screen Shot 2019-11-01 at 9 41 28 AM" src="https://user-images.githubusercontent.com/5697474/68032537-e38f8c00-fc8b-11e9-8326-56ca3a0cdb49.png">

**Comment by sergiogcx** [comment]
It is totally possible that some records do not belong to the 6th and Congress intersection. I do not think empty records default to that address, if that were so we would have seen many thousands of records more being associated to that specific intersection.

**Comment by johnclary** [comment]
yep. you can also see that `MatchLevel` = `city`, so the geocoder is returning the centroid of Austin's city limits. looking at the [dev docs](https://developer.here.com/documentation/geocoder/dev_guide/topics/resource-type-response-geocode.html), here are the `MatchLevel` choices:

- `country`
- `state`
- `county`
- `city`
- `district`
- `street`
- `intersection`
- `houseNumber`
- `postalCode`
- `landmark`

We should probably just handle any geocode where the `Matchlevel` is not `street`, `intersection`, or `houseNumber` as a failed geocode. And it would probably be worth storing the `MatchQuality` in VZD as well.

**Comment by johnclary** [comment]
@mateoclarke i'm curious, are you seeing a similar pattern with the CRIS lat/lons? are an abundance of them located near 6th/congress?

**Comment by amenity** [comment]
Batch update all these values.

**Comment by mateoclarke** [comment]
The remaining work left to do here is capture in this task #402
