### ISSUE TITLE
VZE: Page bombs when you click "edit polygon" from Location details page

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#388]
![Screen Shot 2019-10-31 at 3 41 05 PM](https://user-images.githubusercontent.com/5697474/67984603-189ccf80-fbf5-11e9-9b6f-26d050eb0d38.png)

**Comment by mddilley** [comment]
Fixed in latest release of react-map-gl
https://github.com/uber/react-map-gl/issues/902#issuecomment-548615758
