### ISSUE TITLE
VZD: Update Capybara (ruby) extraction process to Splinter (python)

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#403]
Nightly FTP dumps using APD's existing infrastructure has been ruled out. We're going to request that TxDOT set up for us what they have done for APD. But this will likely be delayed into next year. In the meantime we need to update and deploy our Cabybara container to automate the extraction process from CRIS Share.

**Comment by mateoclarke** [comment]
Decision has been made to migrate from Capybara to Splinter to make the docker container leaner and to keep our stack more Python based. Updating the title to reflect this.

**Comment by sergiogcx** [comment]
This is done, we have gotten rid of capybara and the new etl container is now built by CircleCI, new documentation provided, and new python code (only) is provided.

Also Merged to master, closing.
