### ISSUE TITLE
VZV: Overall Traffic Fatalities (over 10 years)

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#408]
![Screen Shot 2019-09-16 at 9 39 02 AM](https://user-images.githubusercontent.com/5697474/68259168-bda51700-fffe-11e9-84c5-a5d39af92f8c.png)

Might be good to juxtapose against a population growth rate curve

**Comment by JaceDeloney** [comment]
Team decided to only include data from the previous 5 years (rolling basis)
