### ISSUE TITLE
VZV | Summary | Visualization | Fatalities by ASMP Street Level & by Speed Limit

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#409]
![Screen Shot 2019-09-16 at 9 38 31 AM](https://user-images.githubusercontent.com/5697474/68259243-f513c380-fffe-11e9-8a2c-0732844ce169.png)

**Comment by JaceDeloney** [comment]
This information should come from the locations import. We will need to then QA this data from the GIS location data.

**Comment by JaceDeloney** [comment]
Decided to kick this to a future release. On hold.
