### ISSUE TITLE
VZV: Inventory ScraPD for potential visualizations to reproduce

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#411]
https://viz.scrapd.org/apd/

There might also be data available from the police news releases that we don't currently capture and we may want to start doing so. 

Ex of ScraPD data available:
https://github.com/scrapd/datasets/blob/master/datasets/fatalities-2019-augmented.json

**Comment by JaceDeloney** [comment]
Did this last week.
