### ISSUE TITLE
Update VZ(E) staging env subdomain to `visionzero-staging.`

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#413]
- [x] Add domain, Route 53
- [x] Add domain to distribution 
- [x] SSL certificate in AWS
- [x] Auth0, add domain to config
- [ ] remove https://visionzero.austinmobility.io/editor/ record from CloudFront?

**Comment by mateoclarke** [comment]
New staging URL for VZE: https://visionzero-staging.austinmobility.io/editor
New staging URL for VZV: https://visionzero-staging.austinmobility.io/viewer

**Comment by mateoclarke** [comment]
@sergiogcx I'm going to move this into QA/Review. No rush, but could you review the changes I made and make sure it all looks ok. I wasn't sure if I should delete anything from CloudFront or update Route53. It looks like we still have some other paths to staging that we might want to clean up or redirect or just leave as is? 🤷‍♂ 

- vze-staging.austinmobility.io
- visionzero.austinmobility.io (staging)
- vze.austinmobility.io (producton)

**Comment by sergiogcx** [comment]
Closing, it looks great!
