### ISSUE TITLE
VZD: Add new (mid July to end of Oct '19) crash record data

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-vz-data#415]
- Parsing the csv
- Implement specific GraphQL models and insertion rules for each table

So far:

- [x] Crashes Table Inserted
- [ ] Units
- [ ] Primary Person
- [ ] Person
- [ ] Charges

**Comment by amenity** [comment]
@sergiogcx what milestone should this have?

**Comment by JaceDeloney** [comment]
@sergiogcx create a checklist of all tables needed to complete this issue

**Comment by sergiogcx** [comment]
I have been trying to be extra careful not to contaminate our existing data in production. So I have been running extra tests in staging in our old AWS environment.

I have implemented database unique constraints in the Units, Primary Person, Person, Charges, after that we can begin insertion tests there. These insertion tests are ongoing right now.

**Comment by sergiogcx** [comment]
This was completed a while back, closing.
