### ISSUE TITLE
ETL: New Airflow Infrastructure

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#416]
We need a new cloud architecture for Airflow that is performant and scalable, and on budget.

Main requirements:
- [ ] Airflow needs to be able to run docker containers.
- [ ] It needs to stay under budget
- [ ] It can run on AWS or Google Cloud
- [ ] It is easy to run with minimal maintenance.

Some ideas:

AWS:
- [ ] Run Airflow from an AWS EC2 or Lighsail instance, and let it trigger tasks in Fargate
- [ ] Run Airflow on top of a  ECS/EC2 cluster.

Google:
- [ ] Use Google Composer + Google Kubernetes

Hybrid:
- [ ] Run Airflow from AWS EC2/Lightsail and let it run tasks on Kubernetes

** There is no real need for data artifacts (files) to be stored in some SSD file, we can use buckets in AWS or Google as our hard drive.

**Comment by mateoclarke** [comment]
- Setup in a new Lightsail instance on austinmobility AWS
- Set up dag deployment automation

**Comment by sergiogcx** [comment]
I've made @rgreinho part of this discussion, but I will be working directly to implement this new cloud infrastructure.
