### ISSUE TITLE
VZD: New Python ETL for CR3s PDF Retrieval and Automate Deployment

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#417]
- convert Capybara to Splinter
- update S3 storage and deployment to new AWS org

**Comment by sergiogcx** [comment]
This has been done, the CR3 script uploads 500 records every 5 minutes, it will take around 25 hours to finish all of production’s 150k records.

The S3 bucket is in the new org, currently runs in airflow.

**Comment by sergiogcx** [comment]
Merged to master, closing.
