### ISSUE TITLE
VZD: Automate crash geocoding

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#418]
- Find out if Here returns County information (it does)
- Anything with no coordinates
    - maybe only geocode the address
    - Catching 
- Lock edit of lat/lon from geocoder if human has entered lat/lon based on primary lat/long columns.
    - Edge case/race condition
- Explore python libraries for address normalization and cleanup
    - https://github.com/datamade/usaddress
    - https://pypi.org/project/postal-address/

**Comment by mddilley** [comment]
Another library that could help parse addresses remove duplicate elements is https://pypi.org/project/street-address/

To create an acceptance criteria from the geocoder response, we could use Match Quality or Relevance. https://developer.here.com/documentation/geocoder/dev_guide/topics/resource-type-response-geocode.html#resource-type-response-geocode__match-quality

**Comment by sergiogcx** [comment]
So just a few notes that I've been keeping:
- When manually updated a coordinate, the field `geocode_provider` becomes 5 (Manual Q/A), `latitude_primary` and `longitude_primary` are populated with the coordinates as shown in the drag and drop map.

The goal of the geocoder is to find records that present these values:

- `geocoded = 'N'`
- `geocode_provider = 0`
- `geocode_status = 'DEFAULT'`
- `latitude = null` 
- `longitude = null`
- `latitude_geocoded = null`
- `longitude_geocoded = null`

**Comment by sergiogcx** [comment]
We should not assume other providers have match quality provided. In a quick search, I haven't been able to see if google or A&M have the same type of metric in their response).

`geocode_match_quality` as float
`geocode_metadata` as  json

**Comment by JaceDeloney** [comment]
Can we make sure we get an estimate assigned to this?
