### ISSUE TITLE
Purchase Cognos License from Tyler Tech to get CR3s from Brazos

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-vz-data#423]
Per Josh @ Tyler Tech, we can create our own cognos reporting of CR3 data. Which we can schedule to send to us via email. TBD if the emailed report will actually work for us. But Tyler Tech can sell us a cognos license very quickly and walk us through how to create a report.

**Comment by johnclary** [comment]
I just followed up for a second time with Kimberly and Josh.

**Comment by JaceDeloney** [comment]
Waiting for a response from Tyler Tech

**Comment by johnclary** [comment]
Followed up last week to ask for a quote for the integration

**Comment by JaceDeloney** [comment]
I will follow up with them this week.

**Comment by JaceDeloney** [comment]
Followed up on this today.

**Comment by JaceDeloney** [comment]
Follow up on this again this week :D
