### ISSUE TITLE
VZE: "No-Latitude and Longitude" filter seems broken

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-vz-data#426]
Lewis kindly reported an issue with the "No-Latitude and Longitude" filter, it appears to not be working at all?

Looking at both staging and production, every time I enable or disable the filter the graphql query does not update:

![Screen Shot 2019-11-08 at 11.19.43 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/0b5ada2c-cf36-4355-9b3b-9b139b7ce92e)

In production, take a look at record: 17283417 (which Lewis seems to have updated), once you search for it the crashes index page, try to apply a filter and you will see it present no mater wether the filter is applied or not.

**Comment by mddilley** [comment]
Thanks for creating this issue, @sergio. This likely has something to do with the recent refactoring that I did in PR #399. I'll assign myself to this and complete by next Thursday.
