### ISSUE TITLE
Change `Fatality Flag` to `APD Fatality Flag`

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#427]
There are discrepancies in what APD classifies as a fatality vs what ATD classifies as a fatality. For example, APD may not classify a collision as a fatality because it is in a private drive, a suicide, etc. ATD still wants to track these as fatalities. 

The current state in VZE is that the Fatality Flag pulls the APD record. We need to change `Fatality Flag` to `APD Fatality Flag` so that editors have clarity on what classification they are looking at.

**Comment by mddilley** [comment]
Lewis agrees with the following changes:
>The columns that will display in the UI will be: crash_fatal_fl, death_cnt, apd_confirmed_death_count, and apd_confirmed_fatality.
> 
>crash_fatal_fl (flag) – This column is populated from CRIS data. This field is not editable.
 >
>death_cnt (count) – This column is populated from CRIS data. This field is not editable.
>
>apd_confirmed_death_count (count) – This column is populated from a trigger in the database that populates it with the value of death_cnt (data from CRIS). This field is editable.
>
>apd_confirmed_fatality (flag) – This column is populated from a trigger in the database that populates it with either “Y” or “N” based on the value of apd_confirmed_death_count. If apd_confirmed_death_count is equal to 0, the trigger sets this flag to “N”. If apd_confirmed_death_count is greater than 0, the trigger sets this flag to “Y”. This field is not editable
>
>The new column, atd_human_update, will be a flag that populates with either “Y” or “N”. Its value will determine whether incoming CRIS data can overwrite the value of apd_confirmed_death_count or not. The field defaults to “N”, and this value allows incoming CRIS data to overwrite the value in apd_confirmed_death_count. Once a user makes an edit to apd_confirmed_death_count through the editor, atd_human_update will change to “Y” and incoming CRIS data will no longer overwrite the value in apd_confirmed_death_count. This will preserve human edits. We’ll also add a “Reset to CRIS Data” button to enable users to revert the atd_human_update field to “N” (in case of a change made in error).

### Mockup
<img width="622" alt="Screen Shot 2019-11-08 at 11 09 21 AM" src="https://user-images.githubusercontent.com/37249039/68501793-97f95700-0224-11ea-970f-5d43f7ef4456.png">
