### ISSUE TITLE
VZE: Search in GridTable breaks when submitting different searches (without clearing between)

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-vz-data#442]
To reproduce:
1. Go to https://localhost:3000/#/locations/5553969
2. Enter a search string in the search field ("mopac") and then select "Primary Address" as the search field. Then, search.
3. Without clearing, leave the same string in the search field, but change from "Primary Address" to "Secondary Address" and then search. Both filters apply to the query.
4. Clear the search filters, and the "Primary Address" filter remains in the query and cannot be cleared.

### After second search
![Screen Shot 2019-11-14 at 5 54 00 PM](https://user-images.githubusercontent.com/37249039/68905885-42cbb280-0708-11ea-8b41-dcae3d0b058b.png)

### After clearing
![Screen Shot 2019-11-14 at 5 58 16 PM](https://user-images.githubusercontent.com/37249039/68905909-5c6cfa00-0708-11ea-80ec-63c43db22ebb.png)

**Comment by JaceDeloney** [comment]
@mateoclarke  Look into LOE to refactor search function
