### ISSUE TITLE
Investigate why APD official fatal records aren't being included in our data pull

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#445]
Lewis has been verifying APD official records and adjusting the fatal flags for records in the database.  He has found that there are some APD official fatal records that are not in our database. 

We would like to investigate why these records would not be included in our data pull. Side note: Lewis thinks that these records may not be getting submitted to TXDOT by APD? 

Acceptance criteria:
-Identify why the APD official fatal records would not be getting included in our data pull. 
-Outline a scalable process for adding APD official fatal records that are not included in our data pull.

**Comment by mateoclarke** [comment]
email to LL:

> I've looked into the issue you reported about missing records in VZE.
> 
> There are three different scenarios happening from the records you highlighted in yellow...
> 
> 1. Most of these records are in the database, they just don't appear in search results because we have been filtering our search by City ID = 22. 
> 
> The records below are listed in "RURAL TRAVIS COUNTY" & "BUDA".
> You can still access these records by URL hacking using the Crash ID.
> 
> City ID = 1792 "RURAL TRAVIS COUNTY"
> 
> Case ID: 182891458
> Crash ID: 16696892
> https://visionzero.austin.gov/editor/#/crashes/16696892
> 
> Case ID: 182101672
> Crash ID: 16557999
> https://visionzero.austin.gov/editor/#/crashes/16557999
>  
> Case ID: 182041737
> Crash ID: 16556807
> https://visionzero.austin.gov/editor/#/crashes/16556807
> 
> Case ID: 181840847
> Crash ID: 16503066
> https://visionzero.austin.gov/editor/#/crashes/16503066
> 
> Case ID: 180741868
> Crash ID: 17331180
> https://visionzero.austin.gov/editor/#/crashes/17331180
> 
> Case ID: 163581664
> Crash ID: 15511440
> https://visionzero.austin.gov/editor/#/crashes/15511440
> 
> Case ID: 163420429
> Crash ID: 15480638
> https://visionzero.austin.gov/editor/#/crashes/15480638
> 
> Case ID: 161921728
> Crash ID: 15202234
> https://visionzero.austin.gov/editor/#/crashes/15202234
> 
> Case ID (according to the CR3 you attached): 150430844
> Crash ID (according to the CR3 you attached): null
> Case ID in VZD: 150430844
> Crash ID in VZD: 14296473
> https://visionzero.austin.gov/editor/#/crashes/14296473
> 
> Case ID (according to the CR3 you attached): 143610910
> Crash ID (according to the CR3 you attached): null
> Case ID in VZD: 143610910
> Crash ID in VZD: 14201431
> https://visionzero.austin.gov/editor/#/crashes/14201431
> 
> 
> 
> City ID = 56 "BUDA"
> 
> Case ID: 163161707
> Crash ID: 15457782
> https://visionzero.austin.gov/editor/#/crashes/15457782
> 
> ---
> 
> 2. The one below is strange, seems like the CR3 and record numbers you have for it is different from an identical crash we have in the system. I was able to find it by searching by date and comparing CR3s (attached) to see that it is the same record.
> 
> Case ID (according to the CR3 you attached): 181960333
> Crash ID (according to the CR3 you attached): null
> Case ID in VZD: 185028146
> Crash ID in VZD: 16556568
> https://visionzero.austin.gov/editor/#/crashes/16556567
> 
> ---
> 
> 3. This one was not one of the CR3s you attached but on the "APD ask" tab of the Google Sheet
> 
> Case ID in VZD: 151120238
> Crash ID in VZD: 14423154
> https://visionzero.austin.gov/editor/#/crashes/14423154
> 
> ---
> 
> Not in the VZD so I created new records
> 
> Case ID: 14720068 
> - made a record manually: 
> https://visionzero.austin.gov/editor/#/crashes/14720068
> 
> Case ID: 180290542 
> - made a record manually
> https://visionzero.austin.gov/editor/#/crashes/180290542
> 
> 
> 
> Questions for further action:
> 
> - Should we expand our filter beyond City ID = 22 to include "RURAL TRAVIS COUNTY" & "BUDA"? 
> - Do we need to manually edit to two newly created records further?
