### ISSUE TITLE
VZV comparative multi-year line chart of fatalities

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#454]
As a user, I want to be able to compare the number of fatalities that have occurred over the past five years so that I can see the progress the city is or isn't making in achieving its Vision Zero goals.

Requirements:
- Chart should update based on the latest full month of data that we have available. 
- Users should be able to see fatalities and serious injuries--broken out by month--for the past 5 years.
- For the current year, the user should only see YTD numbers; the line should stop at the last full month that we have data for
- For previous years, the line should populate all months. All years should display on a single line chart.
- Users should be able to compare the month totals by year by placing the mouse over each specific month on the graph.
- Older years should display less prominently than more recent years (e.g., line opacity).
- The current year should be the most prominent
- The chart should show the following dynamic text: "As of [last full month], there have been [x] traffic fatalities this year."

There is a great example of how SF shows a comparison between the past five years of fatality data:
https://sfgov.org/scorecards/transportation/traffic-fatalities

An example of a comparative multi-year line chart is attached.
![Screen Shot 2019-11-18 at 11.52.18 AM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/208030ef-d5bb-4430-890f-1479b07f1d7d)

**Comment by tcwcodes** [comment]
Got the basic elements of this complete. Will tinker around with the colors to make the lines more distinguishable and work on the other elements.
<img width="617" alt="Screen Shot 2019-11-22 at 5 36 37 PM" src="https://user-images.githubusercontent.com/35410637/69467728-f824e880-0d4e-11ea-8959-e40816742918.png">

**Comment by tcwcodes** [comment]
Comparing the two charts, now I'm seeing the SF chart is cumulative. I'll make this one cumulative as well.

**Comment by tcwcodes** [comment]
Cumulative version!

![Screen Shot 2019-11-25 at 12.17.35 PM.png](https://images.zenhubusercontent.com/5cf19d09272c387e1f4f2d1f/bed29be0-d59a-4b8f-8ed0-33d1b60de461)
