### ISSUE TITLE
VZE add new "Geocoder Provider" column to crash table

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#458]
When going through their QA/QC processes, our customers need an easy way to see which crash records have or have not been manually updated. We need to add a column to the crash records table that shows which Geocoder Provider the record is using. Expanding this to the Geocoder Provider will help address other use cases in the future. ![Screen Shot 2019-11-18 at 5.36.04 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/ad700d87-6759-4c3a-b753-49c6c80c562e)

**Comment by mateoclarke** [comment]
@JaceDeloney Can you clarify what you meant in attaching this screenshot? I'm thinking there might be a miscommunication about the difference between a database table vs a UI GridTable and I just want to make sure we're all on the same page.

When we talked about updating the Crash table with a new column for a boolean representing "Manually Updated Coordinates", we were talking about a database table update. Is there also a place in the UI we want this new data field displayed? The more I think about this, it feels like this column is redundant to the display features that @mddilley recently added.

![Screen Shot 2019-12-01 at 7.58.01 PM.png](https://images.zenhubusercontent.com/59f0b24ba468affe6df81d8f/3dd72311-a540-487e-93d5-1887f1b9c9fe)

![image.png](https://images.zenhubusercontent.com/59f0b24ba468affe6df81d8f/75d7f588-e4da-4630-a4f6-b1f7e8414ede)

If we wanted to add an advanced filter for our Crashes "GridTable" (thats our component name for the UI), it seems like we could apply that filter where Geocode Provider == 5

Can we chat more about the intent here before I make database changes?

**Comment by JaceDeloney** [comment]
Clarified the requirements with @mateoclarke. 

We would like to add a new column to the grid table that maintains the key-value pair approach that the other columns in the table use. The title (key) of the column should be "Geocode Provider" and the values within that column should be the value in the database. 

When a user manually updates the lat/longs for a given crash, the Geocode Provider should update to Manual Q/A.

**Comment by JaceDeloney** [comment]
As discussed, please also update the "Source" string in the Crash Location Header to "Geocode Provider". This will align the term we are using in the UI with what is already used in the database.
