### ISSUE TITLE
ETL: CRIS Extracted Data: Load Locations into Knack/PostgreSQL

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-vz-data#48]
Write Insertion Script that:
- [ ] Uses Knackpy to load Data into Locations table.
- [ ] Load list into Knack Locations and/or PostgreSQL

- Set up PostgreSQL Table
- Set up Test Knack environment

**Comment by sergiogcx** [comment]
Same as with issue #47, detached from epic until more clarity is provided about the locations data.

**Comment by mateoclarke** [comment]
@sergiogcx, now that we have some clarity, how should we update this issue?

**Comment by mateoclarke** [comment]
@sergiogcx, I'm going to go ahead and close this issue. I don't think its relevant anymore since we aren't using Knack DB and we should create a different ETL task if necessary.
