### ISSUE TITLE
VZD | New non-CR3 collision columns

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#485]
Implement new columns on the Blueform table for economic cost and comprehensive cost.

**Comment by mateoclarke** [comment]
The three columns have been added to the `atd_apd_blueform` SQL tables in both staging and production with default values from the related lookup tables using this SQL code:

```sql
ALTER TABLE "public"."atd_apd_blueform" ADD COLUMN "est_comp_cost" numeric(10,2) DEFAULT '51000';
ALTER TABLE "public"."atd_apd_blueform" ADD COLUMN "est_econ_cost" numeric(10,2) DEFAULT '12376';
ALTER TABLE "public"."atd_apd_blueform" ADD COLUMN "speed_mgmt_points" numeric(10,2) DEFAULT '0.25';
```

![Screen Shot 2019-12-29 at 4.12.14 PM.png](https://images.zenhubusercontent.com/59f0b24ba468affe6df81d8f/14c8c9e2-72cb-4776-8003-5d6dcb9510b2)
