### ISSUE TITLE
VZV: Fatalities by time of day/day of week highlight table

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#505]
Update the current highlight table being used for the static Vision Zero dashboard to allow users to view previous years of data. The user should have the ability to select and view fatality data from previous year that they want to view by tapping on tabs below the chart.

![Screen Shot 2019-12-09 at 2.44.38 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/0e43c743-321d-4e92-8484-852b8ccda9c0)

Organize the year selectors below the highlight table; something like this:
        2014     |     2015     |      2016    |    2017    |      2018    |     2019

**Comment by mddilley** [comment]
Some promising libraries:
https://github.com/arunghosh/react-heatmap-grid#readme
https://github.com/jask-oss/reaviz

These two might be tied too closely to the calendar year
https://github.com/kevinsqi/react-calendar-heatmap#readme
https://github.com/g1eb/reactjs-calendar-heatmap#readme

**Comment by johnclary** [comment]
reaviz looks cool! and, although there's a learning curve with D3, it's a really, really fun API:
http://bl.ocks.org/tjdecke/5558084

**Comment by johnclary** [comment]
maybe a better D3 example: https://observablehq.com/@eliaslevy/d3-heatmap
