### ISSUE TITLE
VZE: Create set of smoke tests

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#512]
Create of a set of tests with the goal of ensuring that the most important functions work. These tests should be run each time a new release is QAd in Stage. If these tests fail, the Product Manager and Team Lead will need to triage the issue to determine whether it should block the release.

**Comment by johnclary** [comment]
Good stuff! We should implement this for our Knack apps as well.

**Comment by JaceDeloney** [comment]
Below is the first round of smoke tests that I put together from the latest v1.3.0 release:

- Gut check dashboard numbers
- Locations page (5 at random)
- Locations search
- Crash page (5 at random)
- Crash search
- Edit coordinates, verify that they save as set in the map view

We will continue to add smoke tests with each new release
