### ISSUE TITLE
Architecture meeting for VZV app

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#54]
- [x] @mateoclarke to schedule

Agenda:
- Postgres
- Knack API + views
- React framework
- Serverless/Faregate

- use cases: data dashboards that we know we'll need

**Comment by sergiogcx** [comment]
@mateoclarke Would you post the pictures here whenever you have a chance? Thanks!

**Comment by mateoclarke** [comment]
![IMG_9984](https://user-images.githubusercontent.com/5697474/61966974-63bd9b80-af91-11e9-8597-0eb907957652.jpg)

![IMG_9983](https://user-images.githubusercontent.com/5697474/61966977-64563200-af91-11e9-92f8-99694dbbcb2f.jpg)

![IMG_9982](https://user-images.githubusercontent.com/5697474/61966978-64563200-af91-11e9-90e8-59f9fbce8724.jpg)

![IMG_9981](https://user-images.githubusercontent.com/5697474/61966979-64563200-af91-11e9-84cc-a8bf4f3764f1.jpg)
