### ISSUE TITLE
VZV | Summary | Visualization | Year over year demographic comparison

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#556]
As a user, I want to be able to see what groups of people in Austin are most at risk to be seriously injured or killed. 

Present three horizontal bar charts that break down fatalities and serious injuries by the following demographic categories:
- Age
- Race
- Gender

For age categories, please use the Census Bureau guidelines.

As referenced in #547, users should be able to be able to see the demographic data broken down by the following views:
- Fatalities only
- Serious injuries only
- Serious injuries and fatalities

Example:
![Screen Shot 2020-02-12 at 4.00.15 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/c8837c69-207a-4543-894b-e1b6c2204e16)

**Comment by JaceDeloney** [comment]
We need to pull data to determine what demographic would be most interesting to the user. Create a report that includes 2019 fatality numbers by the following two demographic categories:

- ethnicity
- age

**Comment by JaceDeloney** [comment]
Create three pie charts within a single component

**Comment by sergiogcx** [comment]
Re-assigned to Tyler, we don’t know when we will be able to count with Rémy’s support next month, Tyler should be able to work on it if he wants to

**Comment by rgreinho** [comment]
Sorry, I should have posted here, but I communicated with @mddilley about this issue over slack. 

Bellow is a copy paste of our conversation:

>Hey Mike!
I hope you’re having a good week end
I started to play with the graph
here is my first attempt (using fake data)

![image](https://user-images.githubusercontent.com/6969134/73793032-27060480-476b-11ea-98c1-a4f093d980f6.png)

>Here are the concerns I have so far:
>1. The title is too long
>2. The graphs are too small
>3. The labels are cropped

>I am going to add the tabs per year like you did for the time of the day
I am going to understand how you fetch the actually data using the side effect
Once I have this I’ll send you another screenshot
Then we could experiment with other options for the pie graph
Like maybe without labels, but a legend bellow it looks better
Or even other types of graphs
Let me know if you have any remark or other ideas :wink:
Also, fun fact, Reaviz is a lib created by a company here in Austin. they are located at the domain and I interviewed with them 2 years ago :slightly_smiling_face:
His author also came to the react meetup to present the lib last year

I'll create a PR once I got the side effect+axios working.

**Comment by mateoclarke** [comment]
@rgreinho, have you made any progress towards getting this PR published? We're looking to get this task complete within the next sprint (starting today) so we are going to re-assign to @tylerwhitson given the time sensitivity.

**Comment by rgreinho** [comment]
Oh, my understanding after talking with @sergiogcx was that you already reassigned the task to Tyler. Therefore I haven't made any progress at all.

**Comment by sergiogcx** [comment]
Yep, thank you @rgreinho 👍 I did reassign. Your efforts are very much appreciated, we will find something fun to work on :)

**Comment by JaceDeloney** [comment]
@tylerwhitson had the idea of adding both percentages and whole numbers to the tooltips experience (For example: `29% (16)`). Still determining whether this should fit into the MVP.
