### ISSUE TITLE
VZE: LocationCrashes table export data for Unit Description does not match table data

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-vz-data#557]
Xavier reported that the data for the `Unit Description` in the exported `.csv` does not match the data in the LocationCrashes table view.  

To align the data represented in these two places, the following changes could be made:

1. The concatenated string in the table column does not represent the number of units involved (each type of mode involved is accurately represented)
2. The concatenated string in the export of unit description does not accurately represent the units involved (quantity is accurate).

### 1. Table shows vehicle types involved in crash but not quantity of each type
Example record:
https://visionzero-staging.austinmobility.io/editor/#/locations/5554677
<img width="1322" alt="Screen Shot 2019-12-23 at 12 04 30 PM" src="https://user-images.githubusercontent.com/37249039/71375166-f420fc00-2582-11ea-9c23-9560aae660d8.png">

### 2. Export does not accurately represent the units involved
Example record:
https://visionzero-staging.austinmobility.io/editor/#/locations/5554229
**Filtered with crash_id = 15857193**
<img width="1084" alt="Screen Shot 2019-12-23 at 1 02 45 PM" src="https://user-images.githubusercontent.com/37249039/71375767-eec4b100-2584-11ea-9daf-69dac572265b.png">

**Comment by JaceDeloney** [comment]
Here is another instance of this issue occurring:

I couldn’t find a single crash involving a motor vehicle and a pedestrian. I believe it should come over as “MOTOR VEHICLE, PEDESTRIAN”.
In the case of a 2 motor vehicle crash, I’m getting “MOTOR VEHICLE, MOTOR VEHICLE, MOTOR VEHICLE”.

Examples of Crash IDs are:
17436815
17368709
17371993
17447543
17368698

In the case of a motor vehicle and a pedestrian involved crash, I’m getting “PEDESTRIAN, PEDESTRIAN”.

Examples of Crash IDs are:
14119428
14133310
14103935
14104007
14104734
