### ISSUE TITLE
ETL: CRIS repair orphan records.

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-vz-data#57]
Not sure how long this is going to take, it sounds simple enough to query for records that do not contain any values in the connection fields, then re-query, gather id of remote record, re-assign to current object, then upload updated record to knack.

This should take a few hours, hopefully not a full day.

**Comment by sergiogcx** [comment]
Not sure how long this is going to take, it sounds simple enough to query for records that do not contain any values in the connection fields, then re-query, gather id of remote record, re-assign to current object, then upload updated record to knack.

This should take a few hours, hopefully not a full day.

**Comment by mateoclarke** [comment]
Just curious, what an orphan record is in this context?

**Comment by sergiogcx** [comment]
Say for example there is a Unit record that should be associated to a Crash record but for some reason it wasn't (either because of bad data, bad code, knack messing up, or simply there is no crash record available) We need to try making that association or at least give us a report of which ones do not have that connection.

**Comment by sergiogcx** [comment]
Detached from EPIC, it is not a requirement for functionality but a nice-to-have. Will put in the back burner since we don't know for sure if we are going to stay with knack.

**Comment by sergiogcx** [comment]
No longer needed, since we aren't using Knack for the CMS.
