### ISSUE TITLE
VZV | Map | High Injury Network Overlay

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#570]
As a user, I want to do be to view the High Injury Network map as an overlay so that I can see the correlation between crashes and the designated high injury network.

The user should only be able to display one overlay on the map at a time. All overlays should be inactive by default.

**Comment by jaime-mckeown** [comment]
Combined High Injury Network REST Service: 
https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/HIN_final_allmodes/FeatureServer/1?token=ApEDUYV2n3pBuKQ1_oNl7JgztiMEAmv0LSimZSgxW5IihGrhULMP9cL5j9HdozJJ2fMz_qiKelLHibKkCHwcR3HD4bLU9jzGotkbFuWwhCVqh_W_BvOjJbeQg4z8UrQGu68K4aLfYQ-6LFoYt1JQBPS1uuiMd5rExfiriPrDK9nuKLFYvfJMEiWo5gMAI6VTt9f-FwqFkHoSw5_HtHDi5twrRAYT9JMunt37_CAzfRPuvItcod78jbfm-KuEXPHp

**Comment by mddilley** [comment]
VectorTileServer for this layer:
https://github.com/cityofaustin/atd-geospatial/issues/545#issuecomment-577866983
