### ISSUE TITLE
VZV | Map | Austin City Council Districts Overlay

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#573]
As a user, I want to be able to see what crashes are occurring in each city council district. When a user selects this overlay, city council polygons should display with a key outlining what each polygon is.

The user should only be able to display one overlay on the map at a time. All overlays should be inactive by default.

**Comment by jaime-mckeown** [comment]
City Council Districts REST Service:
https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/BOUNDARIES_single_member_districts/FeatureServer/0
