### ISSUE TITLE
VZD | SPIKE | Mode Categorization

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#596]
The goal of this SPIKE is to identify all of the tasks that need to be completed to clearly specify the ATD mode  (mode that was used by the person killed or seriously injured).

Requirements:
- There are currently two columns in the db that help us determine the mode. We need to create--at the database level-- a new column that clearly specifies ATD mode (mode that was used by the person killed or seriously injured).
- This may likely need to be made on the unit level. This could also affect how we display all of the modes involved in the crash.
- Propose a schema for how this data should be stored

**Comment by mateoclarke** [comment]
I've scoped out the work I can see us needing to do for this task. The related epic now includes
