### ISSUE TITLE
How might we sync ATD staff updates in our system of record back to the Postgres instance?

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#60]
- In Knack, we're talking about the data flow from importing records from our raw Postgres with CRIS tables into Knack and then either updating the raw Postgres data with new columns or having a distinct copies with processed/edited data. How would we sync these updates without webhooks?

- An alternative we discussed is a different editing interface connected directly to the Postgres tables, an open-source CMS or a custom built client.

**Comment by sergiogcx** [comment]
I have an alternative idea to web-hooks that we can try in Knack that could save us a lot of headaches in the future for this or other projects (if we can make it work): Submit to multiple endpoints with jQuery.

Based on the [jQuery documentation](https://api.jquery.com/submit/), the submit method can be used to prevent the form from submitting until we run some checks. In our case, we would "prevent the submission" from going to Knack until we have the same data sent to one of our endpoints. 


Imagine there are two endpoints:
1) Knack's normal form endpoint: https://api.knack.com/this/is/your/app/knack-endpoint
2) Custom Endpoint: http://execute-ourlambda-function.amazonwebservices.com/v1/our-form-endpoint


Imagine this is what the form looks like in Knack:

```
<form action="javascript:alert( 'success!' );">
  <div>
    <input type="text">
    <input type="submit">
  </div>
</form>
```

```
<script>
$( "form" ).submit(function( event ) {
  // Gathers all the data in this form
 var all_data = $( this ).serialize()

  // Submit the data to our custom endpoint:
  $.post( "https://execute-ourlambda-function.amazonwebservices.com/v1/our-custom-form-endpoint", all_data );

  // On error we could prevent the form submission, or leave commented to continue with the form submission flow:
  // event.preventDefault();
});
</script>
```

**Comment by sergiogcx** [comment]
Closing, since we have opted not to use Knack for now. Let's close this issue and open a new one if needed in the future.
