### ISSUE TITLE
VZV | SPIKE | Data Quality Check

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#601]
We noticed that some of the VZV visualizations are not displaying the same overall fatality numbers. We need to make sure we have consistent data across our VZV components. We should adhere to the same queries and methodologies used in VZE.

We have contacted the VZV team for the official fatality and serious injury numbers that they are using for 2019. This will help us verify data quality.

**Comment by JaceDeloney** [comment]
Attached are the draft 2019 numbers for fatalities and serious injuries. The injury numbers are still coming from Microstrategyand will be different from what the VZ database will house, so when comparing we should be sure we’re looking at the same time frame and seeing how close we are – not aiming for perfect match of serious injury numbers. 

[](url)[https://app.zenhub.com/files/178280308/62f863ac-a76d-493c-a935-81bb7431a243/download](https://app.zenhub.com/files/178280308/62f863ac-a76d-493c-a935-81bb7431a243/download)

**Comment by JaceDeloney** [comment]
Reference issue #614

**Comment by mddilley** [comment]
#### Comparing VZV & VZE data extracts to APD News Releases
- Case # 193510124 https://www.austintexas.gov/news/traffic-fatality-83 (Not in CRIS search)
- Case # 192830834 https://www.austintexas.gov/news/traffic-fatality-67-4 (in VZE but APD fatality count is 0, APD report shows passenger died in crash, CR3 shows “Fatal”)
- Case # 192650413 https://www.austintexas.gov/news/traffic-fatality-65-4 (APD News Release shows 1 death, VZE shows 0)
- Case # 192861035 https://www.austintexas.gov/news/traffic-fatality-66-4 (APD News Release shows 1 death, VZE shows 0)
- Case # 191880028 https://www.austintexas.gov/news/traffic-fatality-39-4 (APD News Release shows 1 death, VZE shows 0)

VZ Team dashboard shows 89 fatalities for 2019. With these 5 records added, `death_cnt` = 89 and `apd_confirmed_fatality_count` = 87.

#### Socrata ETL
- When converting motor vehicle modes to motorcycle modes, the `motor_vehicle_fl` remains as`Y`. This causes all motorcycle fatalities to also count towards motor vehicle fatalities (inflating the total fatality count).

#### Inconsistencies unrelated to fatality counts
- Crash Date mismatch between APD and CRIS Case #193201421 https://www.austintexas.gov/news/traffic-fatality-74-2 (11/16/19 in VZE, 11/18/19 in APD release)
- Case ID mismatch Case # 190881844 https://www.austintexas.gov/news/traffic-fatality-12-4 (19881844 in VZE but fatality is accurate)

**Comment by mddilley** [comment]
@JaceDeloney - do you think we should make an issue for the five fatality records above? Let me know if I can clarify, but I think we need to ask the VZ Team if those 5 records are counted towards the total in the VZ team dashboard. Those 5 records can account for the discrepancy between VZV/VZE and the VZ Team dashboard for 2019 fatalities.

**Comment by mateoclarke** [comment]
@sergiogcx creating this new issue after speaking with X. We can close this issue and move the actionable work into #684

https://github.com/cityofaustin/atd-vz-data/issues/684
