### ISSUE TITLE
Add Fatalities by Time of Day to Summary, fix styling issues

### ISSUE THREAD

**Issue by tcwcodes** [cityofaustin/atd-vz-data#604]
Add existing Fatalities by Time of Day component to summary dashboard. Also make this component and FatalitiesMultiYear component more responsive for smaller devices. Other small fixes.

**Comment by amenity** [comment]
Moving this out of _New Issues_ and into _Review/QA_. @tcwcodes, please add an estimate based on our [new estimate scale](https://docs.google.com/document/d/1XwT87Gc05eIdIkAPFx6wjwjLPLdHSiZfZzR30MwTwBw/edit#heading=h.fejthknr89vh). 👕🙏

**Comment by tcwcodes** [comment]
Thanks, @amenity! Finished! I think I had put an estimate and put it into in progress, but then I realized I made it in the wrong repo, so I moved it and I think all that stuff went away >_<
