### ISSUE TITLE
VZE | Reference new AWS server instance

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#609]
The latest crash record that VZE is currently showing is from 12/8/2019. After a quick investigation, @sergiogcx  realized that VZE isn't referencing the new AWS server. We need to reference the new server instance so that VZE populates with the last crash data.

**Comment by sergiogcx** [comment]
There will be no need to bring the entire database from the old account to the new, I realized all I have to do is to request the entire dataset of December and all of January as of this date. The ETL will process the requests all the same.

**Comment by sergiogcx** [comment]
I have made the requests, the process should run overnight and take some time to finish it.

**Comment by sergiogcx** [comment]
@JaceDeloney it looks like the strategy worked. The data has been updated, and the endpoints have also been fixed. Would you please double check the results and let the VZ team know if this issue is resolved?

**Comment by sergiogcx** [comment]
This was fixed a little while back, closing.
