### ISSUE TITLE
CMS vs Knack research

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#61]
- we need a list of pros and cons of different open-source CMS options vs Knack for the crash data management system.
- considering Python, Wordpress (or other PHP solutions), or Node CMSes
- criteria: sustainability, easy of use and feature creation for non-devs, hosting requirements/costs, database integration with existing ETL, customizability, etc.

**Comment by sergiogcx** [comment]
Closing. I think we covered all bases during our extensive meeting yesterday. A new issue was created to add user stories:

https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-vz-data/72

**Comment by sergiogcx** [comment]
https://drive.google.com/open?id=16j962Q1t7w4gOYAOyQHj2mM8I0Rvm40l
