### ISSUE TITLE
VZD/VZV | Update Socrata export ETL with apd_confirmed fields

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-vz-data#614]
The fatality counts in VZV currently reference `death_count`(CRIS data) in the open dataset. Need to update the ETL to export `apd_confirmed_fatality` flag and `apd_confirmed_death_count` field to reflect the VZ team's edits in the data visualized in VZV.

Also need to find a place for the .csv files used to update columns in the datasets from the Socrata UI.

**Comment by JaceDeloney** [comment]
Reference Issue #601
