### ISSUE TITLE
VZD | Add Canonical Mode Categorization Lookup Table

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#615]
UPDATED:

- [x] Add a new lookup table of ATD Mode Categories (bulleted below) to production & staging DBs using these column headers:
- `atd_mode_category_id`
- `atd_mode_category_mode_name`
- `atd_mode_category_desc` - for what is in parens

---
Here is the ‘wish list’ of modes to that the VZ Team requested that we create. The items in parenthesis is what would be included from the CRIS file. 

- Passenger car (2- and 4-door)
- Large passenger vehicle (Truck/Pickup Truck/SUV/Van)
- Motorcycle
- Motor vehicle – other (all other motor vehicles)
- Bicycle
- Micromobility device
- Pedestrian
- Train
- Other/Unknown (options 5-9, 94)

We need to modify the database to update the mode categories based on the above information so that they display on VZE and VZV.

**Comment by mateoclarke** [comment]
This looks super related to #596 so I'm assigning this one to myself.

**Comment by mateoclarke** [comment]
Creating a new table and inserted values...


```sql
CREATE TABLE "public"."atd__mode_category_lkp" ("id" int4 NOT NULL,"atd_mode_category_mode_name" varchar(128),"atd_mode_category_desc" varchar(128), PRIMARY KEY ("id"));

INSERT INTO "public"."atd__mode_category_lkp" ("id", "atd_mode_category_mode_name", "atd_mode_category_desc") VALUES ('1', 'Passenger car', '(2-door and 4-door)');
INSERT INTO "public"."atd__mode_category_lkp" ("id", "atd_mode_category_mode_name", "atd_mode_category_desc") VALUES ('2', 'Large passenger vehicle', '(Truck/Pickup Truck/SUV/Van)');
INSERT INTO "public"."atd__mode_category_lkp" ("id", "atd_mode_category_mode_name") VALUES ('3', 'Motorcycle');
INSERT INTO "public"."atd__mode_category_lkp" ("id", "atd_mode_category_mode_name", "atd_mode_category_desc") VALUES ('4', 'Motor vehicle – other', '(all other motor vehicles)');
INSERT INTO "public"."atd__mode_category_lkp" ("id", "atd_mode_category_mode_name") VALUES ('5', 'Bicycle');
INSERT INTO "public"."atd__mode_category_lkp" ("id", "atd_mode_category_mode_name") VALUES ('6', 'Micromobility device');
INSERT INTO "public"."atd__mode_category_lkp" ("id", "atd_mode_category_mode_name") VALUES ('7', 'Pedestrian');
INSERT INTO "public"."atd__mode_category_lkp" ("id", "atd_mode_category_mode_name") VALUES ('8', 'Train');
INSERT INTO "public"."atd__mode_category_lkp" ("id", "atd_mode_category_mode_name", "atd_mode_category_desc") VALUES ('9', 'Other/Unknown', '(options 5-9, 94)');

```

**Comment by mateoclarke** [comment]
![Screen Shot 2020-01-29 at 6.00.32 PM.png](https://images.zenhubusercontent.com/59f0b24ba468affe6df81d8f/461c07c8-2bce-4e4e-99de-7d96835e3d87)
