### ISSUE TITLE
Publish subset of crash data to Socrata as "Under Construction" dataset

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#63]
- [x] define columns to publish - @mateoclarke 
- [x] create .csv for upload - @sergiogcx 
- [x] upload to Socrata with publisher credentials - @mateoclarke & @sergiogcx 
- [x] check our 27 columns against what CRIS shares in the public extract @mateoclarke 
- [x] Publish from draft mode

**Comment by mateoclarke** [comment]
@sergiogcx, I know you've done one export to csv but, is it possible to keep the column headers? It seems like that will make it much easier to apply the needed metadata when we upload to Socrata.

Here's a first pass of column headers that seem ok, though also looking for input from @johnclary:
```
Crash_ID            # This seems helpful relating to other possible tables we eventually publish
Crash_Fatal_Fl      # Fatality Flag
Crash_Date
Crash_Time
Case_ID             # I think this relates to a CR3 ID, maybe not necessary for the public data
Rpt_Latitude        # Not sure why there are two sets of lat/lon (I think Rpt means report? so from the CR3?)
Rpt_Longitude
Rpt_Block_Num
Rpt_Street_Pfx
Rpt_Street_Name
Rpt_Street_Sfx
Crash_Speed_Limit
Road_Constr_Zone_Fl     # Construction Zone Flag
Latitude
Longitude
Street_Name
Street_Nbr
Street_Name_2
Street_Nbr_2
Crash_Sev_ID             # References a lookup table
Sus_Serious_Injry_Cnt    # Everything below are counts of injuries
Nonincap_Injry_Cnt
Poss_Injry_Cnt
Non_Injry_Cnt
Unkn_Injry_Cnt
Tot_Injry_Cnt
Death_Cnt
```

**Comment by johnclary** [comment]
Looks good to me.

**Comment by sergiogcx** [comment]
Thank you Mateo, I have re-uploaded the CSV with headers:
https://s3.console.aws.amazon.com/s3/object/atd-visionzero-data/archive/geocoded.austin.crisdata_with_headers.csv?region=us-east-1&tab=overview

**Comment by sergiogcx** [comment]
@mateoclarke showed me how to upload data to Socrata, very easy I should be able to manage that in the future. The UI seems very intuitive and easy to work with.

**Comment by mateoclarke** [comment]
We have a draft dataset ready to publish. We can close this out...

**Comment by johnclary** [comment]
wonderful. we should do a primer on how to update [the data inventory](https://transportation.austintexas.io/open-data/).

**Comment by mateoclarke** [comment]
Reopening this so we remember to check our 27 columns against what CRIS shares in the public extract.

**Comment by mateoclarke** [comment]
Just confirmed that the 27 columns we've decided to focus on are also listed in the Public Extract Specification: https://www.txdot.gov/government/enforcement/data-access.html

**Comment by mateoclarke** [comment]
It's live: https://data.austintexas.gov/Transportation-and-Mobility/-UNDER-CONSTRUCTION-Crash-Report-Data/y2wy-tgr5
