### ISSUE TITLE
VZE | Crash Details Mode info

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#634]
Update VZE Crash Details page to have a new Card that parses the `atd_mode_category_metadata` and renders the data for the user. Card could have a header like: "Killed & Seriously Injured by Mode"

**Comment by JaceDeloney** [comment]
Let's spend some more time understanding the need and user experience here. de-prioritizing

**Comment by JaceDeloney** [comment]
This is something that we could assign Remy, as it is not a time sensitive improvement.
