### ISSUE TITLE
Missing fatality record in VZE

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#638]
Can we search the database for the following Crash ID?
193181630

It is missing in VZE, but the VZ team has a copy of the CR3 in their files. If it is found to be in the database, can we determine why it wasn't added to VZE?

**Comment by mateoclarke** [comment]
@JaceDeloney, this didn't get assigned, estimated or completed in Sprint 16 so I'm moving it into 17 and assigning to myself.

**Comment by JaceDeloney** [comment]
Weird not sure how that one fell through the cracks. Thanks!

**Comment by sergiogcx** [comment]
I will take this one @JaceDeloney  It looks like the Airflow server has been down for the past few days, so it has not been processing new records; so what I did was to restart the server and requested an extract for the past two weeks. We are only going to be importing the new records.

Hopefully we are going to see that record in the database, otherwise I will take a deeper look into it.

**Comment by mddilley** [comment]
@sergiogcx I came across some fatal crash records in the VZV Data Quality Spike (#601) that could be helpful for this issue. These case IDs are in the APD News Releases and can be found in the CRIS database through CRIS Search, but they are not present in VZE production.
- Case # 193200312 https://www.austintexas.gov/news/traffic-fatality-73-3 
- Case # 193020781 https://www.austintexas.gov/news/traffic-fatality-70-3
- Case # 193000691 https://www.austintexas.gov/news/traffic-fatality-69-4
- Case # 192990061 https://www.austintexas.gov/news/traffic-fatality-68-4

**Comment by sergiogcx** [comment]
Thanks @mddilley let me look into them, thanks for working on the data quality spike! :)

**Comment by sergiogcx** [comment]
I have the full data extracts, I will find those records individually and have them inserted today.

**Comment by sergiogcx** [comment]
These are now inserted, sorry for the hiccups this is back in October, November & December when the ETL was in early stages.
