### ISSUE TITLE
Create Read-only Mirrored VZD RDS Instance

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#639]
We need to create a mirrored RDS instance of the Vision Zero db so that Xavier and Frank have more up-to-date VZ data. Access to this RDS instance should be read-only.

Frank will be sending us the IP addresses that need to be whitelisted.

**Comment by sergiogcx** [comment]
The instance is was ordered, it should take a few minutes to go live.

**Comment by sergiogcx** [comment]
The read-replica database is up and running, we just need the IP ranges from Frank for:

- Barton Oaks
- Frank's Home

Also, PowerBI will require exceptions too. I found a list of Microsoft's datacenter ranges:
https://www.microsoft.com/en-us/download/details.aspx?id=41653&751be11f-ede8-5a0c-058c-2ee190a24fa6=True

**Comment by sergiogcx** [comment]
Somewhat related, Xavier also reported an issue in the database with wrong values: https://github.com/cityofaustin/atd-vz-data/issues/646

**Comment by sergiogcx** [comment]
The user had also been created with read-only role, just waiting for IP ranges before I deliver the credentials. 

Closing.
