### ISSUE TITLE
ETL: implement new geocoding engine

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#64]
- [x] evaluate for cost & accuracy
   - Here 
   - Google
   - Esri
   - Texas A&M service
- [x] implement geocoding step in ETL

**Comment by sergiogcx** [comment]
Cool, there are about 19k records that do not have lat/long data.

**Comment by sergiogcx** [comment]
Google:
https://developers.google.com/maps/documentation/geocoding/usage-and-billing
$5 per 1000 requests. It will probably cost us $100 for geocoding with their api.

**Comment by sergiogcx** [comment]
Texas A&M API:

Free for the first 2,500 requests. Gotta pay after that:

![Screen Shot 2019-07-26 at 6.09.41 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/75c5940a-8168-41d8-98b0-816069c5654e)

**Comment by sergiogcx** [comment]
Here's API:

Great free tier: (250k requests per mo)
https://developer.here.com/plans

![Screen Shot 2019-07-26 at 6.10.57 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/66999cad-7087-4827-a5e9-362febdce18f)

**Comment by johnclary** [comment]
Thanks @sergiogcx. Would you run some tests of these services using crash records from CRIS that do not have lat/lng?

**Comment by sergiogcx** [comment]
ArcGIS:

![Screen Shot 2019-07-29 at 9.10.09 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/be287f03-3cdf-4a02-8a47-2152a64fc519)

Pricing Details:
![Screen Shot 2019-07-29 at 9.11.26 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/07f5a017-494e-4537-9649-07e745fc6d8a)

Test:

![Screen Shot 2019-07-29 at 9.09.50 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/55935f58-4f31-410c-a80d-66e5ec9740d8)

Whoa, it looks like they allow up to a million requests per month free with a Dev account. Accuracy seems fair.

**Comment by sergiogcx** [comment]
@johnclary Definitely, I do have a small script in one of my PRs that tests Here's API endpoint.

All there is to do is to make the script gather all records that don't have lat-longs and update each record with whatever Here provides.

I will have the data geocoded by today.

**Comment by mateoclarke** [comment]
Currently, Sergio has geocoded all values missing lat/lon and inserted those new values into the existing `latitude` and `longitude` columns. Should we instead, geocode everything and create new `latitude_here` and `longitude_here` columns. @johnclary do you think this is necessary? Or should we only geocode the values with missing lat/lon values?

Also, we might want to try to clean up the `street_name` column. For many of the highways, they look: 
```
SL0001
US0290
IH0035
```

**Comment by johnclary** [comment]
Yes, I think it's a good idea to preserve the original lat/lon vals. It would also be worthwhile to compare our own geocoding results against what CRIS is providing to see how they're lining up.

Good call on data cleaning, I suspect we'll want to implement a series of cleaning steps for common patterns we see. `IH0035`? Gnarly

**Comment by johnclary** [comment]
also @sergiogcx, we do have our own Esri-hosted geocoders that are loaded with City of Austin streets. Those *should* be free to use. I need to dig up the endpoints...

**Comment by sergiogcx** [comment]
Is data cleaning beyond the scope of this specific issue? I think this issue was about implementing geocoding capabilities in the ETL process, which is done.

Implementing methods that fix our data I think is a separate discussion.

**Comment by mateoclarke** [comment]
@sergiogcx, sure. If you spin out the two issues remaing, that would be fine.

1. geocoding all values, even the ones with existing `latitude`/`longitude` values and create a new `latitude_here`/`longitude_here` column for comparison
2. implement data cleaning on `street_name` column

**Comment by sergiogcx** [comment]
Moving issue to review, we are now working on #445
