### ISSUE TITLE
[Question] Clarify which data will be exposed in admin app vs BI/reporting

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#67]
- confirm that we need Charges table
    - ~500k records in Austin over the past 5 years (1/3 of current Knack records allowed in our subscription plan)

_question for Lewis_

**Comment by johnclary** [comment]
Sample data has been provided to Joel and Lewis for feedback: 

> Lewis and Joel—as discussed, please find attached:
> 
> - CRIS sample data
> - CRIS field list with highlighted fields which are of interest for your crash data management + analysis purposes
> 
> The task for you is to review this data and confirm which of these fields would need to be edited by you, which would need to be viewed on a daily/semi-frequent basis, and which of these fields would only need to be used in aggregate for analysis purposes.
> 
> We are trying to determine which data can be excluded from the end-user "admin" web app versus what would be provided via reporting/BI. 
> 
> 
> Thanks and let us know if you need clarification.

**Comment by johnclary** [comment]
Done. See also [#67](https://github.com/cityofaustin/atd-vz-data/issues/67)

**Comment by mateoclarke** [comment]
Any update on this @johnclary?

**Comment by johnclary** [comment]
no. just followed up. both joel and lewis are out of office.
