### ISSUE TITLE
VZV | Implement rules for displaying five previous years of data

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-vz-data#673]
We have been requested to only show the five previous years of data in VZV. Below are the rules, which should apply to all data being presented in VZV (Summary page and Map page):

VZV should display all of the data for the oldest year. VZV should never display segments of the oldest year. So for example, today (Feb 5, 2020) we would show:

- All months for 2016
- All months for 2017
- All months for 2018
- All months for 2019
- January in 2020

As the year goes on we want to show the end date as the end of the previous month. In January 2021, VZV should display all of 2015 until we hit Feb 2021.

**Comment by mddilley** [comment]
Part of this issue (as applies to Summary mode visualization and map) is addressed in #667.
