### ISSUE TITLE
Non-public data dashboards

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#68]
- Need to discuss and define scope around what dashboards we might need to either embed into the admin website or custom developed that would include confidential data.
- Part of the bigger BI project too.

** EDIT **
I've changed the scope of the issue to include the technical aspects of the dashboards by exploring BI solutions. The actual conversation around the content of the dashboard will be covered in another issue.

**Comment by sergiogcx** [comment]
@mateoclarke and I have just discussed prototyping dashboards with Metabase and QuickSight, that should not be too much of an effort, but it would require a couple hours to test.

We are not committing to either of those two technologies, we are simply trying out these tools to better inform our selection process and determine if these could suit our needs for internal analytics.

**Comment by sergiogcx** [comment]
Metabase creates a bunch of dependency tables (a few dozen) whenever it is spun up, we don't want these tables to live together with our 100+ atd_txdot tables.

I have also been reading about scalability, it looks like was not officially supported (it would only run in 1 server instance) until recently.

To continue:
- [ ] Under the same RDS instance, create a new DB and schema with the purpose of separating metabase's tables from ours.
- [ ] Calculate a good subnet for our metabase cluster, and provide the DB and schema created for metabase.
- [ ] Make sure our current schema (where our atd tables live) is unaffected.

**Comment by sergiogcx** [comment]
Notes on QuickSight:

RDS connections are supported, to test all we have to do is to add to the security settings an exemption for AWS East region IP range:

https://docs.aws.amazon.com/quicksight/latest/user/enabling-access-rds.html

For AWS East, the IP range appears to be: `52.23.63.224/27`
https://docs.aws.amazon.com/quicksight/latest/user/regions.html

**Comment by sergiogcx** [comment]
Metabase has been set up, check your slack for a user name and password.

https://atd-metabase.austintexas.io

Email is not yet configured, so password recovery may not yet work.

**Comment by sergiogcx** [comment]
QuickSight configured:

![Screen Shot 2019-09-03 at 2.21.03 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/1d873aaf-9ae6-4a70-b61a-b285505aafe7)

**Comment by sergiogcx** [comment]
We did some fun test work with visualizations, closing this issue and creating a new one to address the actual content on the dashboards (what exact metrics):

![Screen Shot 2019-09-03 at 2.26.03 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/be54b7b6-80fc-4ca8-b114-aa2ab8476f56)
