### ISSUE TITLE
8/28 VZ Crash Data Sprint Review

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#75]
- [x] schedule wed 8/28 at 3:30
- [x] prep [slides](https://docs.google.com/presentation/d/1p-AhmKT0MnE_wTzq9Njnqa2ckJDms5lsHxLmxZwa4ks/edit#slide=id.g5fb10cf1bb_0_0)

Questions/Discussion Topics:
- confirm what data needs to be exposed in the app
- what columns to present in crash table, 
- which columns need to have support for filtering
- CRIS record updates/QA: what changes are significant (i.e. what columns?) (see #83)
- PII questions and concerns (#104)
- decide what high level summary statistics and data quality issues we want to highlight on the landing page
- further define which tables and details pages are necessary (units, charges, persons, etc)
- brazos login for viewing CR3s

**Comment by mateoclarke** [comment]
Started the deck as a placeholder: https://docs.google.com/presentation/d/1p-AhmKT0MnE_wTzq9Njnqa2ckJDms5lsHxLmxZwa4ks/edit#slide=id.g5fb10cf1bb_0_0

If we have questions or topics we know we need to address, we can go ahead and add them now and format/organize the sliders as we get closer.

**Comment by johnclary** [comment]
My notes (see `TODO`s):

# Sprint Review #3 Notes

### Questions/Comments from VZ Staff

- Searching by street names is fantastic
- Why don't we have current data yet? Sergio: we're waiting until the DB structure is finalized
- Additional fields:
    - At least one or more additional fields per crash which quantify value of life lost, property damage, etc.
- What's the drop-dead date for new features?
- example question: of all the ped crashes on x roadway, how many were fatal, etc.
- are you validating against what you get from a CRIS query on their website vs what's in your database?
    - E.g., How many records changed in the dataset if you pull the data again?
    
### Questions to Staff

- Address Fields: We need Block # + Street Name + Secondary Street (if it exists)

- Crash Table  
    - Add a column that is a concatenation of the different units — (how about icons for each type?)
    - Injury Column: keep as broad as possible. (so, as-is)
    - Search
        - concensus that should have date searching
        - ability to add record tags that we can later search. (need clarification on Joel's comment here)

- Details page: TODO for staff: review and give feedback

- PII:
    - TODO: give a list of PII and share with Joel/Lewis and reccomend which fields we think they should retain
    - TODO: we should flag PII fields in VZD
    - Lewis to ask APD if/how they release CR3s
    - Zipcode is important
    - We don't need the DL # 
    
- Login Roles
    - Probably a read-only viewer field that cannot view PII fields

- QA Workflow
    - Frequent changes from APD: injury severity, toxicology results
    - Going to discuss further after we review what the updates from CRIS look like

- CR3
    - Lewis sent link to G drive for CR3s
    - Going to ask APD for backend access, FTP, or at least a login

- Data Viz:
    - Fatalities, Serious injuries by Mode and Severity and Date
    - years of life lost
    - Total number of crashes, by year, mo
    - Total that need GIS QA
    - On-system vs Off-system (TxDOT vs City) crash counts
    - VZ team to share more

### Persons

- check out person type field (`prsn_type`?) as useful info


### Geocoding

- question for VZ team: what work has already been done, and how do we get that data? e.g., pirority locations for fatality + serious?

### Units, Persons, Charges, etc.

- VZ team: next two months: what kind of analysis do you want to run, and need

### Locations

- layer creation:
    - possibly create a hotspot map of high injuries and fatalities from most recent five years
    - in combination with high-injury network
    - get criteria from engineering
    - create a base polygon layer
    - ideally get 500 locations QA'd
    - TODO: vz team to let us know priority
    - TODO: get frank what he needs

- location attributes
    - what's on the ground today
        - pedestrian crossing, signalization, etc.
        - maybe use intersection points
        - TODO: vz team to provide list of intersection attributes

### MVP

????

**Comment by mateoclarke** [comment]
Closing this one out now that we've made issues from the notes...
