### ISSUE TITLE
Meet to discuss CMS vs Knack for VZA data editing

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-vz-data#77]

**Comment by mateoclarke** [comment]
Yeah, the plan is for @sergiogcx to experiment with PostgREST & Sanic/Flask as REST APIs to interface between the PostgresDB and the custom admin interface (aka VZEditor). #73 #78

We also scoped out some user stories for what we'd need to build out in VZEditor whether we make it in Knack or another more custom interface like [sb admin 2](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2), [sb-admin-react](http://start-react.github.io/sb-admin-react/#/home) or [react-admin](https://github.com/marmelab/react-admin) #72
