### ISSUE TITLE
Vision Zero: Research PostgREST vs Flask/Sanic

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-vz-data#78]
It would be useful to determine if PostgREST can be used instead of Sanic or Flask for our interests.

Main Objectives:
- [x] Data Security (Make sure we have all access control)
- [x] User management and authentication
- [x] Basic CRUD Operations

**Comment by mateoclarke** [comment]
@sergiogcx just a heads up that I moved this issue from `atd-data-tech` to `atd-vz-data`

**Comment by sergiogcx** [comment]
Closing, see #73
