### ISSUE TITLE
Onboard Remy as VZ Volunteer

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#79]
- [ ] [volunteer agreement contract](https://drive.google.com/file/d/1dFyhO86yJmYIb293Ockh9yKdKhc4bcJS/view?usp=sharing) (needs to be finalized by HR)
- [x] calendar item/room reservation for afternoon of Thursday, Aug 22nd
- [ ] scope of work

**Comment by amenity** [comment]
Write/find very basic plain-speak volunteer agreement: 
- Data confidentiality 
- Code contributions are going into public domain

**Comment by mateoclarke** [comment]
@johnclary, @sergiogcx and I discussed this today. We're going to give him some PM leadership experience and give him the responsibility as the main point of contact for Rémy and other potential OA volunteers. 

He's going to check in and use the Github Social Impact SoW as a template (as much as its helpful).

**Comment by johnclary** [comment]
excellent! thanks @sergiogcx @mateoclarke

**Comment by sergiogcx** [comment]
I've started a SoW draft:
https://docs.google.com/document/d/1H-5s8X97Pwy9g-XgS-1pMxzkw4Xam-N1C3TsEv7-UOY/edit#

Will keep working on this during the next few days.

**Comment by sergiogcx** [comment]
This is my final draft, let me know if this needs more work?

https://docs.google.com/document/d/1zyqumvFIV7WWRZXSXR-75xrWZCes_aTwD1F6qeLg7ec/edit?usp=sharing

**Comment by amenity** [comment]
Looks good, @sergiogcx - I polished it a little. Whose signatures does it need, @johnclary ?

**Comment by johnclary** [comment]
ugh

**Comment by sergiogcx** [comment]
Remy will be here on the 27th, we can have him sign those papers then.

**Comment by JaceDeloney** [comment]
This seems like it was completed. Is there anything else that we need to do to close this out?

**Comment by JaceDeloney** [comment]
Talked to Mateo about this last week. We just need Remy to sign the updated document.

**Comment by sergiogcx** [comment]
The docs have been signed, @johnclary I have put them on your desk for your signature.
