### ISSUE TITLE
VZE: Choose an admin theme/library system using React

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#81]
We're planning to use a decoupled client for the VZE frontend. We'd like to keep using React as our FE development framework.

We need to identify, experiment and implement an admin theme/system to facilitate a quick build.

#72 has some listed pages/stories we'd need to build...

searchable/filterable/sortable tables is important, but maybe thats a secondary library and not the admin theme itself.

**Comment by mateoclarke** [comment]
Some options so far:

- [sb admin 2](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2)
- [sb-admin-react](http://start-react.github.io/sb-admin-react/#/home)
- [react-admin](https://github.com/marmelab/react-admin)
- [React-Bootstrap-with-Material-Design](https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design) 
    - [admin theme template](https://github.com/mdbootstrap/Admin-Dashboard-Template-React-Bootstrap)
    - [live example](https://mdbootstrap.com/previews/free-templates/react-admin-dashboard/)
- [react-material-admin](https://github.com/flatlogic/react-material-admin)
- [core-ui-react](https://github.com/coreui/coreui-free-react-admin-template)
- [ant-design-pro](https://pro.ant.design/)
   - [live preview](http://preview.pro.ant.design/)

https://dev.to/sm0ke/react-dashboards-open-source-apps-1c7j

**Comment by mateoclarke** [comment]
Important questions for us are:
- how easy is it to add in data from (and push data to) a GraphQL API
- how many of their component building blocks/themes solve our problems (ex: tables with search, sort, filter)
- how much can we customize components or modify them without going off the rails.

**Comment by sergiogcx** [comment]
After a careful debate, we decided for CoreUI. The main considerations was on how easy it was to customize, load data, and best patterns for development. CoreUI was the clear winner. 

Closing Issue.
