### ISSUE TITLE
VZV: Synthesize notes and survey results from VZA meeting into features/user stories for VZV

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#82]
We attended a Vision Zero Alliance meeting on 8/7/19. We collected some ideas for VZV via discussion and a survey. We need to turn these into actionable tasks

[Google Form Survey](https://docs.google.com/forms/d/1_cUsj-LXVlLIQyyuYTLMqLMLng22f7OWKXBUh_-nXqs/edit)

### Notes from VZA Meeting

- Where have road diets happened?
  - Before & after
  - photos
  - value
- Use of icons vs language for a11y
- Neighborhoods & cooridor reports
  - Contributing factors
- Home ZIP of driver vs where crashes occurred 
  - Anonymize on >= 10 individuals
- Trends over time
  - density
- How are we doing implementing the all ages and abilities network?
  - Other metrics in progress

**Comment by mateoclarke** [comment]
We should also consider NYC VZV features/components as we create user stories for VZV:
https://docs.google.com/document/d/1VrTtb8NrNi1v5c8oVp1_HZrmAK92yfAqGO_ATz9at40/edit#heading=h.cerbnwcigaib

**Comment by mateoclarke** [comment]
Would be good to wrap this up and present outcomes at the next sprint review (but maybe its already a full agenda)? #75

**Comment by mateoclarke** [comment]
@JaceDeloney is our new PM! Have a look through the survey results and we can discuss the next steps and how we might want to synthesize these into user stories or if we want to do that at all.

**Comment by JaceDeloney** [comment]
Taking this on this sprint; combining with the insights gained from interviewing ATD staff.
