### ISSUE TITLE
Set up account with TXDOT for CRIS extracts

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-vz-data#9]
From last email with Lewis:

> For next steps, I wonder if there is value in setting up the account with TxDOT through their website and doing a sample extract for all the fields that we wanted to have and see what we’re working with.  (Combined list of fields requested from ATD staff is below.) Doing this test with some of the 2016 bond top “location” data/info from Boni and starting to relate the data would be interesting as well. 

Website: https://www.txdot.gov/government/enforcement/data-access.html

Guide docs: http://ftp.dot.state.tx.us/pub/txdot-info/trf/crash_statistics/automated/cris-guide.pdf

Fields:
- Case ID
- Date
- Time
- Roadway system
- Roadway part
- Block number and all street info, including speed limit
- Lat/Long
- Unit description (this identifies the motor vehicle, pedestrian, cyclist, etc.)
- Hit and Run
- DL class
- DL restriction
- All Units - address (person)
- All Units - Vehicle year, make, model
- All Units - body style
- All Units - injury severity
- All Units - age, ethnicity, sex, restraint, alcohol/drug specimen, drug test result
- Proof of liability
- Contributing Factors – all which are captured in “Contributing” and “May have”
- Crash severity
- Injury severity
- Intersection-relation type
- Light condition
- Railroad related flag
- Road construction flag
- Crash speed limit
- Active School Zone
- Road type
- Highway system, number, and suffix for both primary and secondary
- On system
- School bus flag
- Toll Road flag
- Traffic control
- Weather condition
- Surface condition
- DWI charge
- Object struck
- Helmet
- Day of week
- Month
- Year
- Collision
- Unit group involved
- Crash type
- Fatality
- PRSN_TYPE_ID

**Comment by mateoclarke** [comment]
Added an attribute to the list above.

email from Lewis:

> One additional field that popped up today as a need for future research (and there will be more!): PRSN_TYPE_ID
> 
> To know which person was the driver – this ties into research we’re doing with municipal court and outcomes of citations.

**Comment by mateoclarke** [comment]
TODO: 
- [ ] identify need for standard (agency) extract vs public extract. Is there PII we need for VZ program or can we still with what is already open to the public?

**Comment by johnclary** [comment]
The login page for the public extract is down. It’s been down for at least two days, but maybe longer. Asked Lewis to ping TxDOT about this or give us a contact to reach out to.

Here’s the broken URL: https://cris.txdot.gov/

**Comment by mateoclarke** [comment]
I was able to get to the URL and request an account. A signed PDF has been sent to them and hopefully I'll get access within the next busy day.

**Comment by mateoclarke** [comment]
I was able to get access and download a test extract. Credentials are stored in our joint vault
